<?php
namespace App\Http\Resources;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
/** Defines the CatalogManagementProductResource class and its project responsibilities. */
class CatalogManagementProductResource extends JsonResource
{
    /** Handles to array for the catalog management product resource workflow. */
    public function toArray(Request $request):array{return ['id'=>$this->public_id,'dbId'=>$this->id,'slug'=>$this->slug,'sku'=>$this->sku,'name'=>$this->name,'shortDescription'=>$this->short_description,'description'=>$this->description,'status'=>$this->status->value,'currency'=>$this->currency,'basePriceMinor'=>$this->base_price_minor,'compareAtPriceMinor'=>$this->compare_at_price_minor,'installmentEnabled'=>$this->installment_enabled,'gameEnabled'=>$this->game_enabled,'taxClassId'=>$this->taxClass?->public_id,'priceIncludesTax'=>$this->price_includes_tax,'rating'=>(float)$this->rating,'reviewsCount'=>$this->reviews_count,'soldCount'=>$this->sold_count,'vendor'=>$this->vendor?['id'=>$this->vendor->id,'name'=>$this->vendor->name,'slug'=>$this->vendor->slug]:null,'category'=>$this->category?['id'=>$this->category->id,'name'=>$this->category->name,'slug'=>$this->category->slug]:null,'images'=>$this->images->map(/** Inline callback for this operation. */ fn($i)=>['id'=>$i->id,'url'=>$i->publicUrl(),'alt'=>$i->alt_text,'managed'=>$i->source==='managed','mediaAssetId'=>$i->mediaAsset?->public_id,'sortOrder'=>$i->sort_order])->all(),'variants'=>$this->variants->map(/** Inline callback for this operation. */ fn($v)=>['id'=>$v->id,'sku'=>$v->sku,'name'=>$v->name,'options'=>$v->option_values??[],'priceMinor'=>$v->price_minor,'compareAtPriceMinor'=>$v->compare_at_price_minor,'isDefault'=>$v->is_default,'isActive'=>$v->is_active,'stock'=>$v->inventories->sum(/** Inline callback for this operation. */ fn($i)=>$i->available()),'onHand'=>$v->inventories->sum('on_hand'),'reserved'=>$v->inventories->sum('reserved'),'safetyStock'=>$v->inventories->sum('safety_stock')])->all(),'createdAt'=>$this->created_at?->toIso8601String(),'updatedAt'=>$this->updated_at?->toIso8601String()];}
}
