<?php
namespace App\Domain\Promotions\Services;
use App\Models\Promotion;
use App\Models\Vendor;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\CarbonImmutable;
use Illuminate\Validation\ValidationException;
/** Defines the PromotionManagementService class and its project responsibilities. */
class PromotionManagementService
{
    /** Handles create for the promotion management service workflow. */
    public function create(array $data, ?Vendor $vendor, bool $admin):Promotion{return DB::transaction(/** Inline callback for this operation. */ fn()=> $this->persist(new Promotion(),$data,$vendor,$admin));}
    /** Handles the update request for this resource. */
    public function update(Promotion $promotion,array $data,?Vendor $vendor,bool $admin):Promotion{return DB::transaction(/** Inline callback for this operation. */ function()use($promotion,$data,$vendor,$admin){$promotion=Promotion::query()->whereKey($promotion->id)->lockForUpdate()->firstOrFail();if(!$admin&&$promotion->vendor_id!==$vendor?->id)abort(404);return $this->persist($promotion,$data,$vendor,$admin);});}
    /** Updates status. */
    public function setStatus(Promotion $promotion,string $status,?Vendor $vendor,bool $admin):Promotion{return DB::transaction(/** Inline callback for this operation. */ function()use($promotion,$status,$vendor,$admin){$promotion=Promotion::query()->whereKey($promotion->id)->lockForUpdate()->firstOrFail();if(!$admin&&$promotion->vendor_id!==$vendor?->id)abort(404);if(!$admin&&$status==='active'&&$promotion->kind==='coupon'&&!$promotion->codes()->where('status','active')->exists())throw ValidationException::withMessages(['status'=>'Coupon promotions need at least one active code before activation.']);$promotion->update(['status'=>$status]);return $promotion->fresh(['vendor','scopes','codes']);});}
    /** Handles persist for the promotion management service workflow. */
    private function persist(Promotion $promotion,array $data,?Vendor $vendor,bool $admin):Promotion
    {
        $isNew=!$promotion->exists;$funding=$admin?($data['fundingMode']??($promotion->funding_mode?:'platform')):'seller';$platformShare=$funding==='platform'?10000:($funding==='seller'?0:(int)($data['platformShareBps']??5000));
        $targetVendorId=$admin?($data['vendorId']??$promotion->vendor_id):$vendor?->id;
        if($admin&&$funding==='seller'&&!$targetVendorId)throw ValidationException::withMessages(['vendorId'=>'Seller-funded promotions must be restricted to a specific vendor.']);
        if(($data['discountType']??$promotion->discount_type)==='percent'&&(int)($data['percentBps']??$promotion->percent_bps)<=0)throw ValidationException::withMessages(['percentBps'=>'Percent discount must be greater than zero.']);
        if(($data['discountType']??$promotion->discount_type)==='fixed'&&(int)($data['fixedMinor']??$promotion->fixed_minor)<=0)throw ValidationException::withMessages(['fixedMinor'=>'Fixed discount must be greater than zero.']);
        $timezone=$data['timezone']??($promotion->timezone?:config('vsn.promotions.default_timezone','UTC'));$starts=!empty($data['startsAt'])?CarbonImmutable::parse($data['startsAt'],$timezone)->utc():$promotion->starts_at;$ends=!empty($data['endsAt'])?CarbonImmutable::parse($data['endsAt'],$timezone)->utc():$promotion->ends_at;if($starts&&$ends&&$ends->lte($starts))throw ValidationException::withMessages(['endsAt'=>'Promotion end must be after its start.']);
        $slug=$data['slug']??($promotion->slug?:Str::slug($data['name']??'promotion').'-'.strtolower(Str::random(6)));
        $attrs=['public_id'=>$promotion->public_id?:((string)Str::ulid()),'vendor_id'=>$targetVendorId,'name'=>$data['name']??$promotion->name,'slug'=>$slug,'kind'=>$data['kind']??($promotion->kind?:'automatic'),'status'=>$data['status']??($promotion->status?:'draft'),'discount_type'=>$data['discountType']??$promotion->discount_type,'percent_bps'=>array_key_exists('percentBps',$data)?$data['percentBps']:$promotion->percent_bps,'fixed_minor'=>array_key_exists('fixedMinor',$data)?$data['fixedMinor']:$promotion->fixed_minor,'minimum_subtotal_minor'=>$data['minimumSubtotalMinor']??($promotion->minimum_subtotal_minor?:0),'stacking_mode'=>$data['stackingMode']??($promotion->stacking_mode?:'stackable'),'can_stack_with_coupon'=>$data['canStackWithCoupon']??($promotion->can_stack_with_coupon??true),'can_stack_with_review_coupon'=>$data['canStackWithReviewCoupon']??($promotion->can_stack_with_review_coupon??false),'funding_mode'=>$funding,'platform_share_bps'=>$platformShare,'priority'=>$data['priority']??($promotion->priority?:0),'max_redemptions'=>array_key_exists('maxRedemptions',$data)?$data['maxRedemptions']:$promotion->max_redemptions,'per_user_limit'=>array_key_exists('perUserLimit',$data)?$data['perUserLimit']:$promotion->per_user_limit,'timezone'=>$timezone,'starts_at'=>$starts,'ends_at'=>$ends,'applies_to_gifts'=>$data['appliesToGifts']??($promotion->applies_to_gifts??false),'metadata'=>array_merge($promotion->metadata??[],['updated_by'=>'promotion_management'])];
        $promotion->fill($attrs)->save();
        if(array_key_exists('scopes',$data)||$isNew){$promotion->scopes()->delete();$scopes=$data['scopes']??[['type'=>'all']];foreach($scopes as $scope){$type=$scope['type']??'all';if(!in_array($type,['all','product','category'],true))continue;$productId=$type==='product'?($scope['id']??null):null;$categoryId=$type==='category'?($scope['id']??null):null;if($productId&&$targetVendorId){$owned=\App\Models\Product::query()->whereKey($productId)->where('vendor_id',$targetVendorId)->exists();if(!$owned)throw ValidationException::withMessages(['scopes'=>'Vendor-restricted promotions can only target products owned by that vendor.']);}$promotion->scopes()->create(['scope_type'=>$type,'product_id'=>$productId,'category_id'=>$categoryId]);}}
        if(array_key_exists('codes',$data)){$normalized=array_values(array_unique(array_filter(array_map(/** Inline callback for this operation. */ fn($x)=>mb_strtoupper(trim((string)$x)),$data['codes']))));foreach($normalized as $value){$taken=\App\Models\PromotionCode::query()->whereRaw('upper(code) = ?',[$value])->where('promotion_id','!=',$promotion->id)->exists();$reviewTaken=\App\Models\ReviewRewardCoupon::query()->whereRaw('upper(code) = ?',[$value])->exists();if($taken||$reviewTaken)throw ValidationException::withMessages(['codes'=>"Promotion code {$value} is already in use."]);}foreach($promotion->codes()->get() as $existingCode){if(in_array(mb_strtoupper($existingCode->code),$normalized,true)){ $existingCode->update(['status'=>'active','max_redemptions'=>$data['codeMaxRedemptions']??$existingCode->max_redemptions,'per_user_limit'=>$data['codePerUserLimit']??$existingCode->per_user_limit]); continue;} $used=\App\Models\PromotionUsage::query()->where('promotion_code_id',$existingCode->id)->exists(); if($used)$existingCode->update(['status'=>'inactive']); else $existingCode->delete();}foreach($normalized as $value){$exists=$promotion->codes()->whereRaw('upper(code) = ?',[$value])->exists();if(!$exists)$promotion->codes()->create(['public_id'=>(string)Str::ulid(),'code'=>$value,'status'=>'active','max_redemptions'=>$data['codeMaxRedemptions']??null,'per_user_limit'=>$data['codePerUserLimit']??null]);}}
        return $promotion->fresh(['vendor','scopes.product','scopes.category','codes']);
    }
}
