<?php
namespace Tests\Feature;
use App\Enums\CartStatus;
use App\Enums\CheckoutStatus;
use App\Enums\OrderStatus;
use App\Enums\PaymentStatus;
use App\Enums\ProductStatus;
use App\Enums\ReviewStatus;
use App\Enums\UserRole;
use App\Models\Cart;
use App\Models\CheckoutSession;
use App\Models\Order;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\Review;
use App\Models\User;
use App\Models\Vendor;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Tests\TestCase;
/** Defines the SearchReviewsMediaLifecycleTest class and its project responsibilities. */
class SearchReviewsMediaLifecycleTest extends TestCase
{
 use RefreshDatabase;
 /** Handles product for the milestone aosearch reviews media test workflow. */
 private function product(?User $seller=null,string $name='AO Search Product'):array{$seller??=User::factory()->create(['role'=>UserRole::Seller->value]);$vendor=Vendor::create(['owner_user_id'=>$seller->id,'name'=>'AO Store '.Str::random(4),'slug'=>'ao-store-'.Str::lower(Str::random(8)),'status'=>'active','commission_bps'=>1000]);$product=Product::create(['public_id'=>(string)Str::ulid(),'vendor_id'=>$vendor->id,'sku'=>'AO-'.Str::upper(Str::random(8)),'slug'=>'ao-product-'.Str::lower(Str::random(8)),'name'=>$name,'short_description'=>'Search lifecycle test product','status'=>ProductStatus::Published,'currency'=>'PKR','base_price_minor'=>100000,'rating'=>4.5,'reviews_count'=>1]);$variant=ProductVariant::create(['product_id'=>$product->id,'sku'=>$product->sku.'-D','name'=>'Default','price_minor'=>100000,'is_default'=>true,'is_active'=>true,'option_values'=>[]]);return[$seller,$vendor,$product,$variant];}
 /** Handles approved review for the milestone aosearch reviews media test workflow. */
 private function approvedReview():array{[$seller,$vendor,$product,$variant]=$this->product();$buyer=User::factory()->create();$cart=Cart::create(['public_id'=>(string)Str::ulid(),'user_id'=>$buyer->id,'status'=>CartStatus::Converted,'currency'=>'PKR']);$session=CheckoutSession::create(['public_id'=>(string)Str::ulid(),'user_id'=>$buyer->id,'cart_id'=>$cart->id,'idempotency_key'=>'ao-'.Str::uuid(),'status'=>CheckoutStatus::Converted,'currency'=>'PKR','address_snapshot'=>['recipient_name'=>$buyer->name,'phone'=>'0300','line1'=>'Street','city'=>'Lahore','country_code'=>'PK'],'shipping_method'=>'standard','payment_method'=>'cod','subtotal_minor'=>100000,'shipping_minor'=>0,'discount_minor'=>0,'coin_redemption_coins'=>0,'coin_redemption_minor'=>0,'total_minor'=>100000,'expires_at'=>now()->addMinutes(15),'converted_at'=>now()]);$order=Order::create(['public_id'=>(string)Str::ulid(),'user_id'=>$buyer->id,'checkout_session_id'=>$session->id,'status'=>OrderStatus::Delivered,'payment_status'=>PaymentStatus::Paid,'payment_method'=>'cod','currency'=>'PKR','subtotal_minor'=>100000,'shipping_minor'=>0,'discount_minor'=>0,'coin_redemption_coins'=>0,'coin_redemption_minor'=>0,'total_minor'=>100000,'placed_at'=>now()->subDays(5),'delivered_at'=>now()->subDays(2)]);$vo=$order->vendorOrders()->create(['public_id'=>(string)Str::ulid(),'vendor_id'=>$vendor->id,'status'=>OrderStatus::Delivered,'currency'=>'PKR','subtotal_minor'=>100000,'shipping_minor'=>0,'discount_minor'=>0,'total_minor'=>100000,'commission_bps'=>1000,'platform_commission_minor'=>10000,'seller_payable_minor'=>90000]);$item=$order->items()->create(['vendor_order_id'=>$vo->id,'product_id'=>$product->id,'product_variant_id'=>$variant->id,'product_name'=>$product->name,'variant_name'=>'Default','sku'=>$variant->sku,'quantity'=>1,'returned_quantity'=>0,'refunded_quantity'=>0,'currency'=>'PKR','unit_price_minor'=>100000,'line_total_minor'=>100000,'selected_options'=>[]]);$review=Review::create(['public_id'=>(string)Str::ulid(),'user_id'=>$buyer->id,'order_id'=>$order->id,'order_item_id'=>$item->id,'product_id'=>$product->id,'product_variant_id'=>$variant->id,'status'=>ReviewStatus::Approved,'rating'=>5,'body'=>'Excellent verified purchase experience for AO testing.','verified_purchase'=>true,'submitted_at'=>now()->subDay(),'moderated_at'=>now()->subHours(20)]);return[$seller,$buyer,$review,$product];}
 /** Verifies search event is recorded and customer can clear recent searches. */
 public function test_search_event_is_recorded_and_customer_can_clear_recent_searches():void{[,,$product]=$this->product(null,'Searchable Mango Device');$user=User::factory()->create();$this->actingAs($user)->getJson('/api/v1/products?q=Searchable+Mango')->assertOk();$this->assertDatabaseHas('catalog_search_events',['user_id'=>$user->id,'normalized_query'=>'searchable mango']);$this->actingAs($user)->getJson('/api/v1/search/recent')->assertOk()->assertJsonPath('data.0.query','Searchable Mango');$this->actingAs($user)->deleteJson('/api/v1/search/recent')->assertOk();$this->assertDatabaseMissing('catalog_search_events',['user_id'=>$user->id]);}
 /** Verifies helpful vote is account scoped and toggle updates count. */
 public function test_helpful_vote_is_account_scoped_and_toggle_updates_count():void{[,,$review]=$this->approvedReview();$user=User::factory()->create();$this->actingAs($user)->postJson("/api/v1/reviews/{$review->public_id}/helpful")->assertOk()->assertJsonPath('data.helpful',true)->assertJsonPath('data.helpfulCount',1);$this->actingAs($user)->postJson("/api/v1/reviews/{$review->public_id}/helpful")->assertOk()->assertJsonPath('data.helpful',false)->assertJsonPath('data.helpfulCount',0);$this->assertDatabaseCount('review_helpful_votes',0);}
 /** Verifies review report enters moderator queue and can be resolved. */
 public function test_review_report_enters_moderator_queue_and_can_be_resolved():void{[,,$review]=$this->approvedReview();$reporter=User::factory()->create();$id=$this->actingAs($reporter)->postJson("/api/v1/reviews/{$review->public_id}/report",['reason'=>'misleading','details'=>'The delivery claim appears unrelated to this product.'])->assertCreated()->json('data.id');$admin=User::factory()->create(['role'=>UserRole::Admin->value]);$this->actingAs($admin)->getJson('/api/v1/admin/reviews/reports?status=pending')->assertOk()->assertJsonPath('data.items.0.id',$id);$this->actingAs($admin)->postJson("/api/v1/admin/reviews/reports/{$id}/resolve",['status'=>'resolved','note'=>'Reviewed by moderator.'])->assertOk()->assertJsonPath('data.status','resolved');$this->assertSame(0,$review->fresh()->report_count);}
 /** Verifies only product seller can reply to approved review. */
 public function test_only_product_seller_can_reply_to_approved_review():void{[$seller,,$review]=$this->approvedReview();$this->actingAs($seller)->postJson("/api/v1/vendor/reviews/{$review->public_id}/reply",['reply'=>'Thank you for your verified feedback.'])->assertOk()->assertJsonPath('data.sellerReply.text','Thank you for your verified feedback.');$other=User::factory()->create(['role'=>UserRole::Seller->value]);Vendor::create(['owner_user_id'=>$other->id,'name'=>'Other AO Store','slug'=>'other-ao-'.Str::lower(Str::random(8)),'status'=>'active','commission_bps'=>1000]);$this->actingAs($other)->postJson("/api/v1/vendor/reviews/{$review->public_id}/reply",['reply'=>'Not my product.'])->assertNotFound();}
 /** Verifies support can view review queue but cannot moderate. */
 public function test_support_can_view_review_queue_but_cannot_moderate():void{[,,$review]=$this->approvedReview();$review->update(['status'=>ReviewStatus::Pending,'moderated_at'=>null]);$support=User::factory()->create(['role'=>UserRole::Support->value]);$this->actingAs($support)->getJson('/api/v1/admin/reviews?status=pending')->assertOk();$this->actingAs($support)->postJson("/api/v1/admin/reviews/{$review->public_id}/moderate",['status'=>'approved'])->assertForbidden();}
 /** Verifies managed product media has hash dimensions and editable alt order. */
 public function test_managed_product_media_has_hash_dimensions_and_editable_alt_order():void{Storage::fake('public');[$seller,,$product]=$this->product();$response=$this->actingAs($seller)->post("/api/v1/vendor/products/{$product->slug}/media",['file'=>UploadedFile::fake()->image('front.jpg',800,800),'alt'=>'Front view'],['Accept'=>'application/json'])->assertCreated();$mediaId=$response->json('data.id');$this->assertNotEmpty($response->json('data.sha256'));$response->assertJsonPath('data.width',800)->assertJsonPath('data.height',800);$this->actingAs($seller)->putJson("/api/v1/vendor/products/{$product->slug}/media/{$mediaId}",['alt'=>'Updated front view','sortOrder'=>3])->assertOk()->assertJsonPath('data.alt','Updated front view')->assertJsonPath('data.sortOrder',3);$this->assertDatabaseHas('product_media_assets',['public_id'=>$mediaId,'alt_text'=>'Updated front view','sort_order'=>3]);}
}
