<?php
namespace App\Http\Controllers\Api\V1;
use App\Domain\Risk\Services\{RiskEvaluator,RiskRecorder};
use App\Enums\UserRole;
use App\Http\Controllers\Controller;
use App\Models\{RiskCase,RiskEvent,RiskHold,RiskProfile,User,Vendor};
use Illuminate\Http\{JsonResponse,Request};
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
/** Defines the AdminRiskController class and its project responsibilities. */
class AdminRiskController extends Controller {
    /** Handles the index request for this resource. */
    public function index(Request $r):JsonResponse{$this->viewer($r);RiskHold::query()->where('status','active')->whereNotNull('expires_at')->where('expires_at','<=',now())->update(['status'=>'expired']);return response()->json(['data'=>[
        'summary'=>['openCases'=>RiskCase::query()->whereIn('status',['open','reviewing'])->count(),'activeHolds'=>RiskHold::query()->where('status','active')->count(),'highRiskUsers'=>RiskProfile::query()->whereNotNull('user_id')->whereIn('level',['high','critical'])->count(),'highRiskVendors'=>RiskProfile::query()->whereNotNull('vendor_id')->whereIn('level',['high','critical'])->count(),'critical'=>RiskProfile::query()->where('level','critical')->count()],
        'profiles'=>RiskProfile::query()->with(['user:id,name,email','vendor:id,name,slug'])->orderByDesc('score')->limit(100)->get()->map(/** Inline callback for this operation. */ fn($p)=>$this->profile($p)),
        'cases'=>RiskCase::query()->with(['user:id,name,email','vendor:id,name,slug','assignee:id,name,email'])->whereIn('status',['open','reviewing'])->orderByRaw("CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END")->latest('opened_at')->limit(100)->get()->map(/** Inline callback for this operation. */ fn($c)=>$this->caseRow($c)),
        'recentEvents'=>RiskEvent::query()->with(['user:id,name,email','vendor:id,name,slug'])->latest('occurred_at')->limit(100)->get()->map(/** Inline callback for this operation. */ fn($e)=>$this->event($e)),
        'holds'=>RiskHold::query()->with(['user:id,name,email','vendor:id,name,slug','creator:id,name,email'])->where('status','active')->latest()->limit(100)->get()->map(/** Inline callback for this operation. */ fn($h)=>$this->holdRow($h)),
        'mode'=>config('vsn.risk.mode','observe'),'autoHoldCritical'=>(bool)config('vsn.risk.auto_hold_critical',false),'reviewScore'=>(int)config('vsn.risk.review_score',50),'criticalScore'=>(int)config('vsn.risk.critical_score',75),
    ]]);}
    /** Handles evaluate user for the admin risk controller workflow. */
    public function evaluateUser(Request $r,User $user,RiskEvaluator $risk):JsonResponse{$this->reviewer($r);return response()->json(['data'=>$this->profile($risk->user($user,'admin_manual'))]);}
    /** Handles evaluate vendor for the admin risk controller workflow. */
    public function evaluateVendor(Request $r,Vendor $vendor,RiskEvaluator $risk):JsonResponse{$this->reviewer($r);return response()->json(['data'=>$this->profile($risk->vendor($vendor,'admin_manual'))]);}
    /** Handles hold for the admin risk controller workflow. */
    public function hold(Request $r,RiskRecorder $events):JsonResponse{$this->reviewer($r);$d=$r->validate(['userId'=>'nullable|integer|exists:users,id','vendorId'=>'nullable|integer|exists:vendors,id','caseId'=>'nullable|string|exists:risk_cases,public_id','scope'=>['required',Rule::in(['all','payments','wallet','games','returns','affiliate','payouts'])],'reason'=>'required|string|min:5|max:2000','expiresAt'=>'nullable|date|after:now']);abort_unless((!empty($d['userId'])) xor (!empty($d['vendorId'])),422,'Choose exactly one user or vendor.');$case=!empty($d['caseId'])?RiskCase::where('public_id',$d['caseId'])->first():null;if($case){abort_if(!empty($d['userId'])&&$case->user_id!==(int)$d['userId'],422,'Risk case belongs to a different user.');abort_if(!empty($d['vendorId'])&&$case->vendor_id!==(int)$d['vendorId'],422,'Risk case belongs to a different vendor.');}$duplicate=RiskHold::query()->where('scope',$d['scope'])->where('status','active')->when(!empty($d['userId']),/** Inline callback for this operation. */ fn($q)=>$q->where('user_id',(int)$d['userId']))->when(!empty($d['vendorId']),/** Inline callback for this operation. */ fn($q)=>$q->where('vendor_id',(int)$d['vendorId']))->where(/** Inline callback for this operation. */ fn($q)=>$q->whereNull('expires_at')->orWhere('expires_at','>',now()))->exists();abort_if($duplicate,422,'An active hold already exists for this scope.');$h=RiskHold::create(['public_id'=>(string)Str::ulid(),'user_id'=>$d['userId']??null,'vendor_id'=>$d['vendorId']??null,'risk_case_id'=>$case?->id,'created_by_user_id'=>$r->user()->id,'scope'=>$d['scope'],'status'=>'active','reason'=>$d['reason'],'starts_at'=>now(),'expires_at'=>$d['expiresAt']??null]);$events->record($h->user,$h->vendor,'manual_risk_hold_created','high',0,$h->scope,'risk_hold',$h->public_id,"risk-hold-created:{$h->public_id}",['actorUserId'=>$r->user()->id,'reason'=>$h->reason]);return response()->json(['data'=>$this->hold($h->load(['user:id,name,email','vendor:id,name,slug','creator:id,name,email']))],201);}
    /** Handles release for the admin risk controller workflow. */
    public function release(Request $r,RiskHold $hold,RiskRecorder $events):JsonResponse{$this->reviewer($r);$d=$r->validate(['note'=>'required|string|min:3|max:2000']);if($hold->status!=='active')return response()->json(['data'=>$this->holdRow($hold->load(['user:id,name,email','vendor:id,name,slug','creator:id,name,email']))]);$hold->update(['status'=>'released','released_by_user_id'=>$r->user()->id,'released_at'=>now(),'release_note'=>$d['note']]);$events->record($hold->user,$hold->vendor,'manual_risk_hold_released','medium',0,$hold->scope,'risk_hold',$hold->public_id,"risk-hold-released:{$hold->public_id}",['actorUserId'=>$r->user()->id,'note'=>$d['note']]);return response()->json(['data'=>$this->holdRow($hold->fresh()->load(['user:id,name,email','vendor:id,name,slug','creator:id,name,email']))]);}
    /** Handles case update for the admin risk controller workflow. */
    public function caseUpdate(Request $r,RiskCase $case):JsonResponse{$this->reviewer($r);$d=$r->validate(['status'=>['required',Rule::in(['open','reviewing','resolved','dismissed'])],'resolution'=>'nullable|string|max:3000','assignedToUserId'=>'nullable|integer|exists:users,id']);$case->update(['status'=>$d['status'],'resolution'=>$d['resolution']??$case->resolution,'assigned_to_user_id'=>$d['assignedToUserId']??$case->assigned_to_user_id,'closed_at'=>in_array($d['status'],['resolved','dismissed'],true)?now():null]);return response()->json(['data'=>$this->caseRow($case->fresh()->load(['user:id,name,email','vendor:id,name,slug','assignee:id,name,email']))]);}
    /** Handles viewer for the admin risk controller workflow. */
    private function viewer(Request $r):void{$v=$r->user()?->role instanceof UserRole?$r->user()->role->value:(string)$r->user()?->role;abort_unless(in_array($v,[UserRole::Support->value,UserRole::Finance->value,UserRole::Moderator->value,UserRole::Admin->value,UserRole::SuperAdmin->value],true),403);}
    /** Handles reviewer for the admin risk controller workflow. */
    private function reviewer(Request $r):void{$v=$r->user()?->role instanceof UserRole?$r->user()->role->value:(string)$r->user()?->role;abort_unless(in_array($v,[UserRole::Moderator->value,UserRole::Admin->value,UserRole::SuperAdmin->value],true),403);}
    /** Handles profile for the admin risk controller workflow. */
    private function profile($p):array{return ['id'=>$p->public_id,'user'=>$p->user?['id'=>$p->user->id,'name'=>$p->user->name,'email'=>$p->user->email]:null,'vendor'=>$p->vendor?['id'=>$p->vendor->id,'name'=>$p->vendor->name,'slug'=>$p->vendor->slug]:null,'score'=>$p->score,'level'=>$p->level,'status'=>$p->status,'signals'=>$p->signal_summary?:[],'lastEvaluatedAt'=>$p->last_evaluated_at?->toIso8601String()];}
    /** Handles case row for the admin risk controller workflow. */
    private function caseRow($c):array{return ['id'=>$c->public_id,'status'=>$c->status,'priority'=>$c->priority,'title'=>$c->title,'summary'=>$c->summary,'scoreAtOpen'=>$c->score_at_open,'resolution'=>$c->resolution,'user'=>$c->user?['id'=>$c->user->id,'name'=>$c->user->name,'email'=>$c->user->email]:null,'vendor'=>$c->vendor?['id'=>$c->vendor->id,'name'=>$c->vendor->name]:null,'assignee'=>$c->assignee?->name,'openedAt'=>$c->opened_at?->toIso8601String(),'closedAt'=>$c->closed_at?->toIso8601String()];}
    /** Handles event for the admin risk controller workflow. */
    private function event($e):array{return ['id'=>$e->public_id,'type'=>$e->event_type,'scope'=>$e->scope,'severity'=>$e->severity,'scoreDelta'=>$e->score_delta,'user'=>$e->user?->email,'vendor'=>$e->vendor?->name,'sourceType'=>$e->source_type,'sourceId'=>$e->source_id,'metadata'=>$e->metadata?:[],'occurredAt'=>$e->occurred_at?->toIso8601String()];}
    /** Handles hold row for the admin risk controller workflow. */
    private function holdRow($h):array{return ['id'=>$h->public_id,'scope'=>$h->scope,'status'=>$h->status,'reason'=>$h->reason,'user'=>$h->user?['id'=>$h->user->id,'name'=>$h->user->name,'email'=>$h->user->email]:null,'vendor'=>$h->vendor?['id'=>$h->vendor->id,'name'=>$h->vendor->name]:null,'createdBy'=>$h->creator?->name,'startsAt'=>$h->starts_at?->toIso8601String(),'expiresAt'=>$h->expires_at?->toIso8601String(),'releasedAt'=>$h->released_at?->toIso8601String()];}
}
