import {useEffect,useState} from 'react';
import SEO from '../components/SEO';
import {Badge,Button,Card,Status} from '../components/Toolkit';
import {apiGet,apiPost} from '../platform/api';
import {useAuth} from '../platform/auth';
const label=/** Handles label for the VSN Ecommerce interface. */ s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,/** Inline callback for this operation. */ m=>m.toUpperCase());
/** Handles acceptance for the VSN Ecommerce interface. */
export default function Acceptance(){
 const {hasPermission}=useAuth();
 const [data,setData]=useState(null),[goLive,setGoLive]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState('');
 const load=/** Handles load for the VSN Ecommerce interface. */ ()=>Promise.all([apiGet('/admin/system/acceptance'),apiGet('/admin/system/go-live')]).then(/** Inline callback for this operation. */ ([acceptance,window])=>{setData(acceptance);setGoLive(window)}).catch(/** Inline callback for this operation. */ e=>setMsg(e.message));
 useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);
 const run=/** Handles run for the VSN Ecommerce interface. */ async(type,fn)=>{setBusy(type);setMsg('');try{await fn();await load()}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const create=/** Handles create for the VSN Ecommerce interface. */ ()=>run('accept',/** Inline callback for this operation. */ ()=>apiPost('/admin/system/acceptance',{}));
 const seal=/** Handles seal for the VSN Ecommerce interface. */ ()=>run('seal',/** Inline callback for this operation. */ ()=>apiPost(`/admin/system/acceptance/${data?.latest?.id}/seal`,{}));
 const sign=/** Handles sign for the VSN Ecommerce interface. */ (area,decision='approved')=>{const comment=window.prompt(`${label(area)} comment (optional)`,'')??'';return run(`sign-${area}`,/** Inline callback for this operation. */ ()=>apiPost(`/admin/system/acceptance/${data?.latest?.id}/signoff`,{area,decision,comment}))};
 const drill=/** Handles drill for the VSN Ecommerce interface. */ ()=>{const rto=Number(window.prompt('Measured restore RTO in minutes','30'));const rpo=Number(window.prompt('Measured RPO in minutes','60'));if(!Number.isFinite(rto)||!Number.isFinite(rpo))return;return run('drill',/** Inline callback for this operation. */ ()=>apiPost('/admin/system/dr-drills',{status:'passed',rto_minutes:rto,rpo_minutes:rpo}))};
 const incident=/** Handles incident for the VSN Ecommerce interface. */ ()=>{const title=window.prompt('Incident title');if(!title)return;return run('incident',/** Inline callback for this operation. */ ()=>apiPost('/admin/system/incidents',{severity:'sev1',type:'production',title}))};
 const resolve=/** Handles resolve for the VSN Ecommerce interface. */ i=>{const summary=window.prompt('Resolution summary');if(!summary)return;return run(`resolve-${i.id}`,/** Inline callback for this operation. */ ()=>apiPost(`/admin/system/incidents/${i.id}/resolve`,{summary}))};
 const openGoLive=/** Handles open go live for the VSN Ecommerce interface. */ ()=>run('go-live-open',/** Inline callback for this operation. */ ()=>apiPost('/admin/system/go-live',{}));
 const observeGoLive=/** Handles observe go live for the VSN Ecommerce interface. */ ()=>run('go-live-observe',/** Inline callback for this operation. */ ()=>apiPost(`/admin/system/go-live/${goLive?.current?.window?.id}/observe`,{}));
 const signGoLive=/** Handles sign go live for the VSN Ecommerce interface. */ area=>{const comment=window.prompt(`${label(area)} stabilization comment (optional)`,'')??'';return run(`go-live-sign-${area}`,/** Inline callback for this operation. */ ()=>apiPost(`/admin/system/go-live/${goLive?.current?.window?.id}/signoff`,{area,decision:'approved',comment}))};
 const recordRollback=/** Handles record rollback for the VSN Ecommerce interface. */ ()=>{const target=window.prompt('Rollback target release');if(!target)return;const note=window.prompt('Rollback evidence / reason');if(!note)return;return run('go-live-rollback',/** Inline callback for this operation. */ ()=>apiPost(`/admin/system/go-live/${goLive?.current?.window?.id}/rollback`,{targetRelease:target,note}))};
 const checks=data?.current?.checks||[], latest=data?.latest, required=data?.current?.requiredSignoffs||[], rc=data?.releaseCandidate||data?.goLive?.releaseCandidate;
 const windowState=goLive?.current, win=windowState?.window, latestObs=windowState?.latestObservation, stabilizationRequired=windowState?.requiredSignoffs||[];
 return <><SEO title="Production Acceptance | VSN Ecommerce"/><div className="content-page"><h1>Production Acceptance</h1><p>Final release evidence, independent approvals, and post-launch stabilization for the exact sealed candidate.</p>{msg&&<Status>{msg}</Status>}
 <div className="metric-grid"><Card><small>Automated blockers</small><strong>{data?.current?.blockersCount??'—'}</strong><span>{data?.current?.status||'loading'}</span></Card><Card><small>Go-live gate</small><strong>{data?.goLive?.ready?'READY':'BLOCKED'}</strong><span>{data?.goLive?.acceptanceFresh?'Acceptance fresh':'Fresh approval required'}</span></Card><Card><small>Launch window</small><strong>{win?label(win.status):'NOT OPEN'}</strong><span>{win?`Release ${win.release}`:'Open only after the sealed go-live gate is READY'}</span></Card><Card><small>Healthy observations</small><strong>{windowState?.consecutiveHealthy??0}/{windowState?.requiredHealthy??'—'}</strong><span>{windowState?.readyForSignoff?'Ready for stabilization sign-off':'Monitoring'}</span></Card></div>
 <Card><h2>1. Automated acceptance</h2>{hasPermission('acceptance.manage')&&<div className="form-row"><Button disabled={!!busy} onClick={create}>{busy==='accept'?'Running…':'Create acceptance run'}</Button><Button variant="secondary" disabled={!!busy} onClick={drill}>Record DR drill evidence</Button><Button variant="secondary" disabled={!!busy} onClick={incident}>Declare SEV1</Button></div>}<div className="status-stack">{checks.map(/** Inline callback for this operation. */ c=><Status key={c.code} ok={c.status==='pass'}><b>{label(c.code)}</b> · {c.status.toUpperCase()} · {c.message}</Status>)}</div></Card>
 <Card><h2>2. Independent pre-launch sign-offs</h2><p>Sign-offs attach to the frozen acceptance run. Evidence drift requires a new run.</p><div className="simple-list">{required.map(/** Inline callback for this operation. */ a=>{const s=latest?.signoffs?.find(/** Inline callback for this operation. */ x=>x.area===a);return <div key={a}><span><b>{label(a)}</b><small>{s?`${s.decision} · ${new Date(s.signedAt).toLocaleString()}`:'Awaiting authorized signer'}</small></span>{s?<Badge tone={s.decision==='approved'?'success':'danger'}>{s.decision}</Badge>:hasPermission('acceptance.sign')?<Button disabled={!latest||latest.blockersCount>0||!!busy} onClick={/** Inline callback for this operation. */ ()=>sign(a)}>Approve</Button>:<Badge>View only</Badge>}</div>})}</div></Card>
 <Card><h2>3. Final release-candidate seal</h2><p>The seal binds deployment, artifact, dependency locks, runtime verification and the approved acceptance snapshot.</p><div className="simple-list"><div><span><b>{rc?`Sealed · ${rc.release}`:'Not sealed'}</b><small>{rc?`Manifest ${rc.manifestSha256?.slice(0,16)}… · Artifact ${rc.artifactSha256?.slice(0,16)}… · ${new Date(rc.sealedAt).toLocaleString()}`:'Complete all pre-launch sign-offs, then seal the exact release candidate.'}</small></span>{rc?<Badge tone="success">SEALED</Badge>:hasPermission('acceptance.seal')?<Button disabled={!latest||latest.status!=='approved'||!!busy} onClick={seal}>{busy==='seal'?'Sealing…':'Seal release candidate'}</Button>:null}</div></div></Card>
 <Card><h2>4. Go-live & stabilization window</h2><p>Opening the window freezes the sealed release identity. Scheduler observations monitor production until the configured stabilization period and consecutive-health requirement pass.</p>{!win&&hasPermission('acceptance.manage')&&<Button disabled={!data?.goLive?.ready||!!busy} onClick={openGoLive}>{busy==='go-live-open'?'Opening…':'Open go-live window'}</Button>}{win&&<><div className="finance-grid"><div><small>Status</small><strong>{label(win.status)}</strong></div><div><small>Rollback window</small><strong>{windowState?.rollbackWindowOpen?'OPEN':'CLOSED'}</strong></div><div><small>Stabilization due</small><strong>{windowState?.stabilizationDue?'YES':'NO'}</strong></div><div><small>Critical incidents</small><strong>{windowState?.criticalIncidents??0}</strong></div></div>{latestObs&&<div className="status-stack"><Status ok={latestObs.status==='healthy'}><b>Observation #{latestObs.sequence}</b> · {latestObs.status.toUpperCase()} · {latestObs.blockerCount} blockers · {latestObs.warningCount} warnings · {new Date(latestObs.observedAt).toLocaleString()}</Status>{(latestObs.blockers||[]).map(/** Inline callback for this operation. */ b=><Status key={b.code}><b>{label(b.code)}</b> · {b.message}</Status>)}</div>}<div className="form-row">{hasPermission('acceptance.manage')&&win.status==='monitoring'&&<Button variant="secondary" disabled={!!busy} onClick={observeGoLive}>Record observation now</Button>}{hasPermission('acceptance.manage')&&['monitoring','failed'].includes(win.status)&&<Button variant="danger" disabled={!!busy} onClick={recordRollback}>Record rollback</Button>}</div><div className="simple-list">{stabilizationRequired.map(/** Inline callback for this operation. */ a=>{const s=win.signoffs?.find(/** Inline callback for this operation. */ x=>x.area===a);return <div key={a}><span><b>{label(a)} stabilization</b><small>{s?`${s.decision} · ${new Date(s.signedAt).toLocaleString()}`:windowState?.readyForSignoff?'Ready for authorized approval':'Waiting for stabilization evidence'}</small></span>{s?<Badge tone={s.decision==='approved'?'success':'danger'}>{s.decision}</Badge>:hasPermission('acceptance.sign')?<Button disabled={!windowState?.readyForSignoff||!!busy} onClick={/** Inline callback for this operation. */ ()=>signGoLive(a)}>Approve stable</Button>:<Badge>View only</Badge>}</div>})}</div></>}</Card>
 <Card><h2>5. Incident status</h2><div className="simple-list">{(data?.incidents||[]).map(/** Inline callback for this operation. */ i=><div key={i.id}><span><b>{i.severity.toUpperCase()} · {i.title}</b><small>{i.type} · {i.status} · {new Date(i.startedAt).toLocaleString()}</small></span>{hasPermission('acceptance.manage')&&!['resolved','closed'].includes(i.status)&&<Button variant="secondary" disabled={!!busy} onClick={/** Inline callback for this operation. */ ()=>resolve(i)}>Resolve</Button>}</div>)}</div></Card>
 </div></>;
}
