import {useEffect,useState} from 'react';
import {Badge,Button,Card,Field,SectionHeader,Select,Status} from '../components/Toolkit';
import {apiGet,apiPost} from '../platform/api';

const Page=/** Handles page for the VSN Ecommerce interface. */ ({title,sub,children})=><div className="simple-page admin-page"><div className="page-title"><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{children}</div>;
const when=/** Handles when for the VSN Ecommerce interface. */ v=>v?new Date(v).toLocaleString():'—';
const tone=/** Handles tone for the VSN Ecommerce interface. */ s=>['active','credited','fulfilled','winner_selected','open'].includes(s)?'success':['suspended','closed','cancelled','reversed'].includes(s)?'danger':['pending','available','scheduled','closed'].includes(s)?'warning':'neutral';

/** Handles admin loyalty for the VSN Ecommerce interface. */
export function AdminLoyalty(){
 const [summary,setSummary]=useState(null),[wallets,setWallets]=useState([]),[accounts,setAccounts]=useState([]),[commissions,setCommissions]=useState([]),[q,setQ]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const load=/** Handles load for the VSN Ecommerce interface. */ async()=>{setError('');try{const [s,w,a,c]=await Promise.all([apiGet('/admin/engagement/summary'),apiGet(`/admin/engagement/wallets?q=${encodeURIComponent(q)}`),apiGet('/admin/engagement/affiliate/accounts'),apiGet('/admin/engagement/affiliate/commissions')]);setSummary(s);setWallets(w.items||[]);setAccounts(a||[]);setCommissions(c.items||[])}catch(e){setError(e.message)}};
 useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);
 const adjust=/** Handles adjust for the VSN Ecommerce interface. */ async user=>{const raw=prompt('Coins adjustment. Positive = credit, negative = debit.');if(!raw)return;const coins=Number(raw);if(!Number.isInteger(coins)||coins===0)return setError('Enter a non-zero whole number.');const reason=prompt('Reason for audited adjustment');if(!reason)return;const expires=coins>0?prompt('Optional expiry in days. Leave blank for default promotional expiry.') : '';setBusy(`w${user.userId}`);try{await apiPost(`/admin/engagement/wallets/users/${user.userId}/adjust`,{coins,reason,expiresInDays:expires?Number(expires):null});setMsg('Immutable wallet adjustment posted.');await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const status=/** Handles status for the VSN Ecommerce interface. */ async(a,next)=>{const reason=prompt(`Reason for ${next}`);if(!reason)return;setBusy(`a${a.id}`);try{await apiPost(`/admin/engagement/affiliate/accounts/${a.id}/status`,{status:next,reason});setMsg('Affiliate status event recorded.');await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const process=/** Handles process for the VSN Ecommerce interface. */ async()=>{setBusy('process');try{const r=await apiPost('/admin/engagement/affiliate/process',{limit:500});setMsg(`Affiliate processing: ${r.accruedOrders} orders accrued, ${r.matured} matured, ${r.credited} credited.`);await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const expire=/** Handles expire for the VSN Ecommerce interface. */ async()=>{setBusy('expire');try{const r=await apiPost('/admin/engagement/wallets/expire',{limit:1000});setMsg(`${r.processed} due coin lot(s) processed.`);await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 return <Page title="VSN Coins & Affiliate" sub="Operate wallet ledger, promotional expiry and affiliate commissions without editing historical transactions.">{error&&<Status>{error}</Status>}{msg&&<Status ok>{msg}</Status>}
  <div className="metric-grid"><Card><small>Wallet balance</small><strong>{Number(summary?.wallet?.balanceCoins||0).toLocaleString()}</strong><span>{Number(summary?.wallet?.reservedCoins||0).toLocaleString()} reserved</span></Card><Card><small>Expiring in 30 days</small><strong>{Number(summary?.wallet?.expiring30Days||0).toLocaleString()}</strong><span>promotional coins</span></Card><Card><small>Affiliate accounts</small><strong>{summary?.affiliate?.activeAccounts||0}</strong><span>{Number(summary?.affiliate?.pendingCoins||0).toLocaleString()} pending coins</span></Card><Card><small>Affiliate credited</small><strong>{Number(summary?.affiliate?.creditedCoins||0).toLocaleString()}</strong><span>lifetime credited coins</span></Card></div>
  <Card><SectionHeader title="Customer wallets" sub="Manual adjustments create immutable admin_adjustment ledger transactions."/><div className="admin-filter-row"><input value={q} onChange={/** Inline callback for this operation. */ e=>setQ(e.target.value)} onKeyDown={/** Inline callback for this operation. */ e=>e.key==='Enter'&&load()} placeholder="Customer name or email"/><Button variant="secondary" onClick={load}>Search</Button><Button variant="secondary" disabled={busy==='expire'} onClick={expire}>Process due expiries</Button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Balance</th><th>Reserved</th><th>Available</th><th>Expiring 30d</th><th>Next expiry</th><th></th></tr></thead><tbody>{wallets.map(/** Inline callback for this operation. */ w=><tr key={w.userId}><td><b>{w.name}</b><small>{w.email}</small></td><td>{Number(w.balanceCoins).toLocaleString()}</td><td>{Number(w.reservedCoins).toLocaleString()}</td><td>{Number(w.availableCoins).toLocaleString()}</td><td>{Number(w.expiring30Days).toLocaleString()}</td><td>{when(w.nextExpiryAt)}</td><td><Button disabled={busy===`w${w.userId}`} onClick={/** Inline callback for this operation. */ ()=>adjust(w)}>Adjust</Button></td></tr>)}{!wallets.length&&<tr><td colSpan="7">No wallets found.</td></tr>}</tbody></table></div></Card>
  <Card><SectionHeader title="Affiliate accounts" action="Process commissions"/><div className="button-row"><Button disabled={busy==='process'} onClick={process}>Accrue / mature / credit now</Button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Member</th><th>Code</th><th>Referrals</th><th>Status</th><th>Terms</th><th>Actions</th></tr></thead><tbody>{accounts.map(/** Inline callback for this operation. */ a=><tr key={a.id}><td><b>{a.name}</b><small>{a.email}</small></td><td>{a.referralCode}</td><td>{a.referralsCount}</td><td><Badge tone={tone(a.status)}>{a.status}</Badge></td><td>{a.termsVersion}</td><td><div className="button-row">{a.status!=='active'&&a.status!=='closed'&&<Button onClick={/** Inline callback for this operation. */ ()=>status(a,'active')}>Activate</Button>}{a.status==='active'&&<Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>status(a,'suspended')}>Suspend</Button>}{a.status!=='closed'&&<Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>status(a,'closed')}>Close</Button>}</div></td></tr>)}{!accounts.length&&<tr><td colSpan="6">No affiliate accounts.</td></tr>}</tbody></table></div></Card>
  <Card><SectionHeader title="Recent affiliate commissions"/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Beneficiary</th><th>Order</th><th>Level</th><th>Rate</th><th>Coins</th><th>Status</th><th>Available</th></tr></thead><tbody>{commissions.slice(0,100).map(/** Inline callback for this operation. */ c=><tr key={c.id}><td><b>{c.beneficiary?.name}</b><small>{c.beneficiary?.email}</small></td><td>{c.orderId}</td><td>L{c.level}</td><td>{c.rate}%</td><td>{Number(c.rewardCoins).toLocaleString()}</td><td><Badge tone={tone(c.status)}>{c.status}</Badge></td><td>{when(c.availableAt)}</td></tr>)}{!commissions.length&&<tr><td colSpan="7">No commissions.</td></tr>}</tbody></table></div></Card>
 </Page>
}

/** Handles admin games for the VSN Ecommerce interface. */
export function AdminGames(){
 const [games,setGames]=useState([]),[entries,setEntries]=useState([]),[selected,setSelected]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const [form,setForm]=useState({productSlug:'',entryCoins:70,maxEntries:'',maxEntriesPerUser:100,winnerBonusCoins:0,opensAt:'',closesAt:'',announcementAt:''});
 const load=/** Handles load for the VSN Ecommerce interface. */ ()=>apiGet('/admin/engagement/games').then(setGames).catch(/** Inline callback for this operation. */ e=>setError(e.message)); useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);
 const create=/** Handles create for the VSN Ecommerce interface. */ async()=>{setBusy('create');setError('');try{await apiPost('/admin/games',{...form,entryCoins:Number(form.entryCoins),maxEntries:form.maxEntries?Number(form.maxEntries):null,maxEntriesPerUser:form.maxEntriesPerUser?Number(form.maxEntriesPerUser):null,winnerBonusCoins:Number(form.winnerBonusCoins||0),opensAt:new Date(form.opensAt).toISOString(),closesAt:new Date(form.closesAt).toISOString(),announcementAt:new Date(form.announcementAt).toISOString()});setMsg('Game Win campaign created with committed draw secret.');await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const action=/** Handles action for the VSN Ecommerce interface. */ async(g,path,body={},label='Updated.')=>{setBusy(g.id);try{await apiPost(path,body);setMsg(label);await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const viewEntries=/** Handles view entries for the VSN Ecommerce interface. */ async g=>{setSelected(g);try{const x=await apiGet(`/admin/engagement/games/${g.id}/entries`);setEntries(x.items||[])}catch(e){setError(e.message)}};
 return <Page title="Game Win Operations" sub="Create campaigns, cap abuse, audit entries/draw evidence and fulfill winner rewards.">{error&&<Status>{error}</Status>}{msg&&<Status ok>{msg}</Status>}
  <Card><SectionHeader title="Create campaign"/><div className="form-grid"><Field label="Product slug" value={form.productSlug} onChange={/** Inline callback for this operation. */ e=>setForm({...form,productSlug:e.target.value})}/><Field label="Entry coins" type="number" value={form.entryCoins} onChange={/** Inline callback for this operation. */ e=>setForm({...form,entryCoins:e.target.value})}/><Field label="Max total entries" type="number" value={form.maxEntries} onChange={/** Inline callback for this operation. */ e=>setForm({...form,maxEntries:e.target.value})}/><Field label="Max entries / user" type="number" value={form.maxEntriesPerUser} onChange={/** Inline callback for this operation. */ e=>setForm({...form,maxEntriesPerUser:e.target.value})}/><Field label="Winner bonus coins" type="number" value={form.winnerBonusCoins} onChange={/** Inline callback for this operation. */ e=>setForm({...form,winnerBonusCoins:e.target.value})}/><Field label="Opens at" type="datetime-local" value={form.opensAt} onChange={/** Inline callback for this operation. */ e=>setForm({...form,opensAt:e.target.value})}/><Field label="Closes at" type="datetime-local" value={form.closesAt} onChange={/** Inline callback for this operation. */ e=>setForm({...form,closesAt:e.target.value})}/><Field label="Announcement at" type="datetime-local" value={form.announcementAt} onChange={/** Inline callback for this operation. */ e=>setForm({...form,announcementAt:e.target.value})}/></div><Button disabled={busy==='create'||!form.productSlug||!form.opensAt||!form.closesAt||!form.announcementAt} onClick={create}>Create Game Win</Button></Card>
  <Card><SectionHeader title="Campaigns"/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Prize</th><th>Status</th><th>Entry</th><th>Entries</th><th>User cap</th><th>Bonus</th><th>Draw</th><th>Actions</th></tr></thead><tbody>{games.map(/** Inline callback for this operation. */ g=><tr key={g.id}><td><b>{g.product?.name}</b><small>{g.product?.slug}</small></td><td><Badge tone={tone(g.status)}>{g.status}</Badge></td><td>{Number(g.entryCoins).toLocaleString()}</td><td>{g.totalEntries}{g.maxEntries?` / ${g.maxEntries}`:''}</td><td>{g.maxEntriesPerUser||'—'}</td><td>{Number(g.winnerBonusCoins||0).toLocaleString()}</td><td>{g.draw?<><b>#{g.draw.winningTicketNumber}</b><small>{g.draw.selectionHash?.slice(0,12)}…</small></>:'—'}</td><td><div className="button-row"><Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>viewEntries(g)}>Entries</Button>{['scheduled','open'].includes(g.status)&&<Button variant="secondary" disabled={busy===g.id} onClick={/** Inline callback for this operation. */ ()=>action(g,`/admin/games/${g.id}/close`)}>Close</Button>}{g.status==='closed'&&<Button disabled={busy===g.id} onClick={/** Inline callback for this operation. */ ()=>action(g,`/admin/games/${g.id}/draw`,{},'Winner drawn from immutable snapshot.')}>Draw</Button>}{!['fulfilled','cancelled'].includes(g.status)&&<Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>{const reason=prompt('Cancellation reason');if(reason)action(g,`/admin/games/${g.id}/cancel`,{reason},'Campaign cancelled; entry refunds queued.')}}>Cancel</Button>}{g.status==='cancelled'&&<Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>action(g,`/admin/games/${g.id}/refunds/process`,{},'Cancelled entries refund batch processed.')}>Refund entries</Button>}{g.status==='winner_selected'&&<Button onClick={/** Inline callback for this operation. */ ()=>{const reference=prompt('Prize handoff/shipment reference')||'';action(g,`/admin/games/${g.id}/fulfill`,{method:'manual_handoff',reference},'Prize fulfilled and winner bonus credited.') }}>Fulfill</Button>}</div></td></tr>)}{!games.length&&<tr><td colSpan="8">No Game Win campaigns.</td></tr>}</tbody></table></div></Card>
  {selected&&<Card><SectionHeader title={`Entries · ${selected.product?.name}`} sub={`${entries.length} entry records loaded`}/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Quantity</th><th>Coins</th><th>Entered</th><th>Refund</th><th>Risk evidence</th></tr></thead><tbody>{entries.map(/** Inline callback for this operation. */ e=><tr key={e.id}><td><b>{e.user?.name}</b><small>{e.user?.email}</small></td><td>{e.quantity}</td><td>{Number(e.coinsSpent).toLocaleString()}</td><td>{when(e.enteredAt)}</td><td>{e.refunded?'refunded':'—'}</td><td><small>IP {e.ipHash?.slice(0,10)||'—'} · UA {e.userAgentHash?.slice(0,10)||'—'}</small></td></tr>)}</tbody></table></div></Card>}
 </Page>
}
