import {useEffect,useMemo,useState} from "react";
import SEO from "../components/SEO";
import {Badge,Button,Card,Field,Select,Status} from "../components/Toolkit";
import {apiDelete,apiGet,apiPost,apiPut,apiUrl} from "../platform/api";

const money=/** Handles money for the VSN Ecommerce interface. */ (n,c="PKR")=>new Intl.NumberFormat(undefined,{style:"currency",currency:c,maximumFractionDigits:0}).format((Number(n)||0)/100);
const pct=/** Handles pct for the VSN Ecommerce interface. */ bps=>`${((Number(bps)||0)/100).toFixed(1)}%`;
const size=/** Handles size for the VSN Ecommerce interface. */ n=>!n?"—":n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const title=/** Handles title for the VSN Ecommerce interface. */ s=>String(s||"").replaceAll("_"," ").replace(/\b\w/g,/** Inline callback for this operation. */ m=>m.toUpperCase());

/** Handles admin analytics for the VSN Ecommerce interface. */
export default function AdminAnalytics(){
  const today=new Date().toISOString().slice(0,10), defaultFrom=new Date(Date.now()-29*86400000).toISOString().slice(0,10);
  const [filters,setFilters]=useState({from:defaultFrom,to:today,timezone:"Asia/Karachi",currency:"PKR"});
  const [data,setData]=useState(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  const [reportType,setReportType]=useState("executive_summary");
  const [schedule,setSchedule]=useState({name:"Monthly executive report",report_type:"executive_summary",cadence:"monthly",timezone:"Asia/Karachi",run_at_local:"08:00",weekday:1,day_of_month:1,period:"previous_month",enabled:true});
  const query=useMemo(/** Inline callback for this operation. */ ()=>new URLSearchParams(filters).toString(),[filters]);
  const load=/** Handles load for the VSN Ecommerce interface. */ ()=>apiGet(`/admin/analytics?${query}`).then(setData).catch(/** Inline callback for this operation. */ e=>setMsg(e.message));
  useEffect(/** Inline callback for this operation. */ ()=>{load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const run=/** Handles run for the VSN Ecommerce interface. */ async fn=>{setBusy(true);setMsg("");try{await fn();await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}};
  const exportNow=/** Handles export now for the VSN Ecommerce interface. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost('/admin/analytics/exports',{reportType,format:'csv',filters}));
  const createSchedule=/** Handles create schedule for the VSN Ecommerce interface. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost('/admin/analytics/schedules',{...schedule,filters:{period:schedule.period,timezone:schedule.timezone,currency:filters.currency}}));
  const toggleSchedule=/** Handles toggle schedule for the VSN Ecommerce interface. */ s=>run(/** Inline callback for this operation. */ ()=>apiPut(`/admin/analytics/schedules/${s.id}`,{enabled:!s.enabled}));
  const deleteSchedule=/** Handles delete schedule for the VSN Ecommerce interface. */ s=>run(/** Inline callback for this operation. */ ()=>apiDelete(`/admin/analytics/schedules/${s.id}`));
  const a=data?.analytics,c=a?.commerce||{},f=a?.finance||{},l=a?.liabilities||{};
  return <><SEO title="Business Intelligence | VSN Ecommerce"/><main className="content-page"><h1>Business Intelligence & Reports</h1><p>Ledger-derived marketplace reporting. Promotion performance is attribution, not causal incrementality.</p>{msg&&<Status>{msg}</Status>}
    <Card><h2>Reporting window</h2><div className="form-grid"><Field label="From" type="date" value={filters.from} onChange={/** Inline callback for this operation. */ e=>setFilters({...filters,from:e.target.value})}/><Field label="To" type="date" value={filters.to} onChange={/** Inline callback for this operation. */ e=>setFilters({...filters,to:e.target.value})}/><Field label="Timezone" value={filters.timezone} onChange={/** Inline callback for this operation. */ e=>setFilters({...filters,timezone:e.target.value})}/><Field label="Currency" value={filters.currency} onChange={/** Inline callback for this operation. */ e=>setFilters({...filters,currency:e.target.value.toUpperCase()})}/></div><Button disabled={busy} onClick={load}>Refresh analytics</Button></Card>
    <div className="metric-grid"><Card><small>GMV / paid order value</small><strong>{money(c.gmvMinor??c.paidOrderValueMinor,a?.range?.currency)}</strong><span>{c.orders||0} orders</span></Card><Card><small>Net order value</small><strong>{money(c.netOrderValueMinor,a?.range?.currency)}</strong><span>{money(c.completedRefundMinor,a?.range?.currency)} completed refunds</span></Card><Card><small>Platform net revenue</small><strong>{money(f.platformNetRevenueMinor,a?.range?.currency)}</strong><span>Commission less platform-funded subsidy</span></Card><Card><small>Repeat buyer rate</small><strong>{pct(c.repeatBuyerRateBps)}</strong><span>{c.repeatCustomers||0} repeat buyers</span></Card></div>
    <div className="two-col"><Card><h2>Economics</h2><div className="simple-list"><Metric name="Merchandise gross" value={money(c.merchandiseGrossMinor,a?.range?.currency)}/><Metric name="Discounts" value={money(c.discountMinor,a?.range?.currency)}/><Metric name="Platform commission" value={money(f.platformCommissionRevenueMinor,a?.range?.currency)}/><Metric name="Platform promotion subsidy" value={money(f.platformSubsidyExpenseMinor,a?.range?.currency)}/><Metric name="Seller payouts paid" value={money(f.sellerPayoutPaidMinor,a?.range?.currency)}/><Metric name="Tax collected" value={money(a?.tax?.collectedMinor,a?.range?.currency)}/></div></Card><Card><h2>Current liabilities</h2><div className="simple-list"><Metric name="VSN Coin liability" value={money(l.vsnCoinLiabilityMinor,a?.range?.currency)}/><Metric name="Coins outstanding" value={(l.vsnCoinsOutstanding||0).toLocaleString()}/><Metric name="Affiliate pending liability" value={money(l.affiliatePendingLiabilityMinor,a?.range?.currency)}/><Metric name="Game prize liability" value={money(l.gamePrizeLiabilityMinor,a?.range?.currency)}/><Metric name="Manual refunds pending" value={money(c.manualRefundPendingMinor,a?.range?.currency)}/></div></Card></div>
    <Card><h2>Daily trend</h2><div className="simple-list">{(a?.trends||[]).slice(-31).map(/** Inline callback for this operation. */ r=><div key={r.date}><span><b>{r.date}</b><small>{r.orders} orders · refunds {money(r.refundMinor,a?.range?.currency)}</small></span><strong>{money(r.paidOrderValueMinor,a?.range?.currency)}</strong></div>)}</div></Card>
    <div className="two-col"><Card><h2>Top sellers</h2><div className="simple-list">{(a?.sellers||[]).slice(0,10).map(/** Inline callback for this operation. */ s=><div key={`${s.vendorId}-${s.vendor}`}><span><b>{s.vendor}</b><small>{s.orders} orders · commission {money(s.platformCommissionMinor,a?.range?.currency)}</small></span><strong>{money(s.orderValueMinor,a?.range?.currency)}</strong></div>)}</div></Card><Card><h2>Promotion attribution</h2><div className="simple-list">{(a?.promotions||[]).slice(0,10).map(/** Inline callback for this operation. */ p=><div key={p.promotionId||p.name}><span><b>{p.name}</b><small>{p.orders} orders · discount {money(p.discountMinor,a?.range?.currency)} · {p.returnOnDiscountBps?`${(p.returnOnDiscountBps/10000).toFixed(2)}× value/discount`:'—'}</small></span><strong>{money(p.attributedOrderValueMinor,a?.range?.currency)}</strong></div>)}</div></Card></div>
    <Card><h2>Customer cohorts</h2><div className="simple-list">{(a?.customers||[]).map(/** Inline callback for this operation. */ r=><div key={r.cohort}><span><b>{r.cohort}</b><small>{r.newCustomers} new · {r.repeatWithin30Days} repeated within 30 days</small></span><strong>{pct(r.repeatWithin30DaysBps)}</strong></div>)}</div></Card>
    <Card><h2>Private CSV exports</h2><p>Exports are generated from authoritative records, stored privately, checksum-verified and automatically expired.</p><div className="form-row"><Select value={reportType} onChange={/** Inline callback for this operation. */ e=>setReportType(e.target.value)}>{(data?.reportTypes||[]).map(/** Inline callback for this operation. */ t=><option key={t} value={t}>{title(t)}</option>)}</Select><Button disabled={busy} onClick={exportNow}>Queue CSV export</Button></div><div className="simple-list">{(data?.exports||[]).map(/** Inline callback for this operation. */ e=><div key={e.id}><span><b>{title(e.reportType)}</b><small><Badge>{e.status}</Badge> · {e.rowsCount||0} rows · {size(e.sizeBytes)} · {e.createdAt?new Date(e.createdAt).toLocaleString():''}{e.error?` · ${e.error}`:''}</small></span>{e.downloadUrl?<a className="button secondary" href={apiUrl(e.downloadUrl.replace('/api/v1',''))}>Download</a>:<span>{e.status==='queued'||e.status==='processing'?'Processing…':'—'}</span>}</div>)}</div></Card>
    <Card><h2>Scheduled reports</h2><p>Scheduled exports stay inside the authenticated private report center; arbitrary external email recipients are intentionally not supported.</p><div className="form-grid"><Field label="Name" value={schedule.name} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,name:e.target.value})}/><Select label="Report" value={schedule.report_type} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,report_type:e.target.value})}>{(data?.reportTypes||[]).map(/** Inline callback for this operation. */ t=><option key={t} value={t}>{title(t)}</option>)}</Select><Select label="Cadence" value={schedule.cadence} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,cadence:e.target.value})}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></Select><Field label="Run at" type="time" value={schedule.run_at_local} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,run_at_local:e.target.value})}/><Field label="Timezone" value={schedule.timezone} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,timezone:e.target.value})}/><Select label="Report period" value={schedule.period} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,period:e.target.value})}><option value="last_7_days">Rolling last 7 days</option><option value="last_30_days">Rolling last 30 days</option><option value="month_to_date">Month to date</option><option value="previous_month">Previous calendar month</option></Select>{schedule.cadence==='weekly'&&<Field label="ISO weekday (1–7)" type="number" value={schedule.weekday} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,weekday:Number(e.target.value)})}/>} {schedule.cadence==='monthly'&&<Field label="Day of month (1–28)" type="number" value={schedule.day_of_month} onChange={/** Inline callback for this operation. */ e=>setSchedule({...schedule,day_of_month:Number(e.target.value)})}/>}</div><Button disabled={busy} onClick={createSchedule}>Create schedule</Button><div className="simple-list">{(data?.schedules||[]).map(/** Inline callback for this operation. */ s=><div key={s.id}><span><b>{s.name}</b><small>{title(s.reportType)} · {s.cadence} · next {s.nextRunAt?new Date(s.nextRunAt).toLocaleString():'disabled'}</small></span><span><Button variant="secondary" disabled={busy} onClick={/** Inline callback for this operation. */ ()=>toggleSchedule(s)}>{s.enabled?'Disable':'Enable'}</Button> <Button variant="secondary" disabled={busy} onClick={/** Inline callback for this operation. */ ()=>deleteSchedule(s)}>Delete</Button></span></div>)}</div></Card>
    {a?.definitions&&<Card><h2>Metric definitions</h2>{Object.entries(a.definitions).map(/** Inline callback for this operation. */ ([k,v])=><p key={k}><b>{title(k)}:</b> {v}</p>)}</Card>}
  </main></>;
}
/** Handles metric for the VSN Ecommerce interface. */
function Metric({name,value}){return <div><span><b>{name}</b></span><strong>{value}</strong></div>}
