import { useEffect, useState } from "react";
import SEO from "../components/SEO";
import { Button, Card, Field, SectionHeader, Select, Status } from "../components/Toolkit";
import { apiGet, apiPost, apiPut } from "../platform/api";

const initial={name:"",slug:"",ownerUserId:"",status:"active",commissionBps:1000};
/** Handles admin vendors for the VSN Ecommerce interface. */
export default function AdminVendors(){
 const [rows,setRows]=useState([]),[owners,setOwners]=useState([]),[form,setForm]=useState(initial),[error,setError]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const load=/** Handles load for the VSN Ecommerce interface. */ async()=>{try{const [v,u]=await Promise.all([apiGet('/admin/vendors'),apiGet('/admin/users?role=seller&perPage=100')]);setRows(v?.items||[]);setOwners(u?.items||[]);setError("");}catch(e){setError(e.message)}};
 useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);
 const create=/** Handles create for the VSN Ecommerce interface. */ async()=>{setBusy(true);setError("");setMsg("");try{await apiPost('/admin/vendors',{...form,ownerUserId:Number(form.ownerUserId),commissionBps:Number(form.commissionBps)});setForm(initial);setMsg('Vendor created.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const setStatus=/** Handles set status for the VSN Ecommerce interface. */ async(v,status)=>{try{await apiPut(`/admin/vendors/${v.id}`,{status});await load()}catch(e){setError(e.message)}};
 return <><SEO title="Vendors | VSN Ecommerce Admin"/><div className="simple-page admin-page"><div className="page-title"><h1>Vendor Management</h1><p>Create seller stores and control marketplace status.</p></div>{error&&<Status>{error}</Status>}{msg&&<Status ok>{msg}</Status>}<Card><SectionHeader title="Create vendor"/><div className="form-grid"><Field label="Store name" value={form.name} onChange={/** Inline callback for this operation. */ e=>setForm({...form,name:e.target.value})}/><Field label="Slug (optional)" value={form.slug} onChange={/** Inline callback for this operation. */ e=>setForm({...form,slug:e.target.value})}/><Select label="Seller owner" value={form.ownerUserId} onChange={/** Inline callback for this operation. */ e=>setForm({...form,ownerUserId:e.target.value})}><option value="">Choose seller</option>{owners.map(/** Inline callback for this operation. */ u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</Select><Field label="Commission (basis points)" type="number" min="0" max="10000" value={form.commissionBps} onChange={/** Inline callback for this operation. */ e=>setForm({...form,commissionBps:e.target.value})}/></div><Button disabled={busy||!form.name||!form.ownerUserId} onClick={create}>{busy?'Creating…':'Create vendor'}</Button></Card><Card><SectionHeader title="Marketplace vendors"/><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Store</th><th>Owner</th><th>Status</th><th>Commission</th><th>Products</th></tr></thead><tbody>{rows.map(/** Inline callback for this operation. */ v=><tr key={v.id}><td><b>{v.name}</b><small>{v.slug}</small></td><td>{v.owner?.name}<small>{v.owner?.email}</small></td><td><select value={v.status} onChange={/** Inline callback for this operation. */ e=>setStatus(v,e.target.value)}><option value="active">active</option><option value="pending">pending</option><option value="suspended">suspended</option></select></td><td>{(Number(v.commissionBps||0)/100).toFixed(2)}%</td><td>{v.productsCount||0}</td></tr>)}</tbody></table></div></Card></div></>;
}
