import { useEffect, useState } from "react";
import SEO from "../components/SEO";
import { Button, Card, Field, SectionHeader, Select, Status } from "../components/Toolkit";
import { apiGet, apiPost, apiPut } from "../platform/api";

const roles = ["customer","seller","seller_staff","support","finance","moderator","admin","super_admin"];
const initial = {name:"",email:"",password:"",role:"customer",emailVerified:true};

/** Handles admin users for the VSN Ecommerce interface. */
export default function AdminUsers(){
 const [rows,setRows]=useState([]),[meta,setMeta]=useState({}),[form,setForm]=useState(initial),[query,setQuery]=useState(""),[role,setRole]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[msg,setMsg]=useState("");
 const load=/** Handles load for the VSN Ecommerce interface. */ async()=>{try{const p=new URLSearchParams();if(query)p.set('q',query);if(role)p.set('role',role);const data=await apiGet(`/admin/users${p.toString()?`?${p}`:''}`);setRows(data?.items||[]);setMeta(data?.meta||{});setError("");}catch(e){setError(e.message)}};
 useEffect(/** Inline callback for this operation. */ ()=>{load()},[role]);
 const create=/** Handles create for the VSN Ecommerce interface. */ async()=>{setBusy(true);setError("");setMsg("");try{await apiPost('/admin/users',form);setForm(initial);setMsg('User created successfully.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const changeRole=/** Handles change role for the VSN Ecommerce interface. */ async(user,next)=>{try{await apiPut(`/admin/users/${user.id}`,{role:next});await load()}catch(e){setError(e.message)}};
 return <><SEO title="Users | VSN Ecommerce Admin"/><div className="simple-page admin-page"><div className="page-title"><h1>User Management</h1><p>Create accounts, assign roles and review marketplace access.</p></div>{error&&<Status>{error}</Status>}{msg&&<Status ok>{msg}</Status>}
 <Card><SectionHeader title="Create user" sub="Admin-created users can sign in immediately."/><div className="form-grid"><Field label="Full name" value={form.name} onChange={/** Inline callback for this operation. */ e=>setForm({...form,name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={/** Inline callback for this operation. */ e=>setForm({...form,email:e.target.value})}/><Field label="Temporary password" type="password" value={form.password} onChange={/** Inline callback for this operation. */ e=>setForm({...form,password:e.target.value})}/><Select label="Role" value={form.role} onChange={/** Inline callback for this operation. */ e=>setForm({...form,role:e.target.value})}>{roles.map(/** Inline callback for this operation. */ r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</Select></div><label className="ui-field checkbox-field"><span>Email verified</span><input type="checkbox" checked={form.emailVerified} onChange={/** Inline callback for this operation. */ e=>setForm({...form,emailVerified:e.target.checked})}/></label><Button disabled={busy||!form.name||!form.email||form.password.length<10} onClick={create}>{busy?'Creating…':'Create user'}</Button></Card>
 <Card><SectionHeader title="Users" sub={`${meta.total||rows.length} accounts`}/><div className="admin-filter-row"><input aria-label="Search users by name or email" value={query} onChange={/** Inline callback for this operation. */ e=>setQuery(e.target.value)} onKeyDown={/** Inline callback for this operation. */ e=>e.key==='Enter'&&load()} placeholder="Search name or email"/><select aria-label="Filter users by role" value={role} onChange={/** Inline callback for this operation. */ e=>setRole(e.target.value)}><option value="">All roles</option>{roles.map(/** Inline callback for this operation. */ r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><Button variant="secondary" onClick={load}>Search</Button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Verified</th><th>Created</th></tr></thead><tbody>{rows.map(/** Inline callback for this operation. */ u=><tr key={u.id}><td><b>{u.name}</b><small>#{u.id}</small></td><td>{u.email}</td><td><select aria-label={`Role for ${u.name}`} value={u.role} onChange={/** Inline callback for this operation. */ e=>changeRole(u,e.target.value)}>{roles.map(/** Inline callback for this operation. */ r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></td><td>{u.emailVerified?'Yes':'No'}</td><td>{u.createdAt?new Date(u.createdAt).toLocaleDateString():'—'}</td></tr>)}</tbody></table></div></Card></div></>;
}
