import {Link} from 'react-router-dom';
import {FaBolt,FaCoins,FaShieldAlt,FaTruck,FaUndo,FaGamepad,FaArrowRight,FaStore,FaGift,FaClock,FaMobileAlt,FaLaptop,FaHome,FaTshirt,FaHeart,FaStar} from 'react-icons/fa';
import SEO from '../components/SEO';
import ProductCard from '../components/ProductCard';
import {products,categories,games} from '../data/catalog';
import {Card,SectionHeader,Countdown,SafeImage} from '../components/Toolkit';
import {useStore} from '../platform/store';
import {apiBackend,apiGet} from '../platform/api';
import {useLaravelWallet} from '../platform/wallet';
import {useLaravelGames} from '../platform/games';
import {getBuyAgain,getRecommendations,getRecentlyViewed} from '../platform/personalization';
import {getDeals} from '../platform/promotions';
import {normalizeLaravelProduct} from '../platform/catalog';
import {useEffect,useState} from 'react';
import {useUX} from '../components/UXProvider';
const iconMap={Mobiles:<FaMobileAlt/>,Laptops:<FaLaptop/>,Home:<FaHome/>,Fashion:<FaTshirt/>};
/** Handles home for the VSN Ecommerce interface. */
export default function Home({onAdd}){const {toast}=useUX();const s=useStore();const [personal,setPersonal]=useState({recommended:[],recent:[],buyAgain:[]});const [dealItems,setDealItems]=useState([]);const [market,setMarket]=useState({categories:[],vendors:[],products:[]});const lw=useLaravelWallet();const lg=useLaravelGames();const liveGames=apiBackend==='laravel'?lg.games.filter(/** Keeps only server-authorized active or scheduled games. */ g=>['open','scheduled'].includes(g.status)).map(/** Maps server games into the home-card shape. */ g=>({id:g.id,name:g.product?.name,slug:g.product?.slug,image:g.product?.image,announcementAt:g.announcementAt,entryCoins:g.entryCoins})):games;const walletCoins=apiBackend==='laravel'?(lw.wallet?.balanceCoins||0):s.coinBalance;const walletValue=apiBackend==='laravel'?(lw.wallet?.valueRupees||0):s.coinsToRs(s.coinBalance);const decorateGameProduct=/** Handles decorate game product for the VSN Ecommerce interface. */ p=>{if(apiBackend!=='laravel')return p;const slug=String(p.name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');const g=liveGames.find(/** Inline callback for this operation. */ x=>x.slug===slug);return g?{...p,game:true,gameEntryCoins:g.entryCoins,announcementAt:g.announcementAt}:p};useEffect(/** Inline callback for this operation. */ ()=>{if(apiBackend!=='laravel')return;Promise.allSettled([getRecommendations(8),getRecentlyViewed(4),getBuyAgain(4)]).then(/** Inline callback for this operation. */ ([a,b,c])=>setPersonal({recommended:a.status==='fulfilled'?(a.value.items||[]):[],recent:b.status==='fulfilled'?(b.value.items||[]):[],buyAgain:c.status==='fulfilled'?(c.value.items||[]):[]}))},[]);useEffect(/** Inline callback for this operation. */ ()=>{if(apiBackend!=='laravel')return;getDeals(4).then(/** Inline callback for this operation. */ x=>setDealItems(x.items||[])).catch(/** Inline callback for this operation. */ ()=>{})},[]);useEffect(/** Loads server-authoritative public categories, sellers and popular products for home fallbacks. */ ()=>{if(apiBackend!=='laravel')return;Promise.allSettled([apiGet('/categories'),apiGet('/vendors'),apiGet('/products?sort=popular&perPage=12')]).then(/** Stores only real API-backed marketplace rows. */ ([cats,vendors,products])=>setMarket({categories:cats.status==='fulfilled'?(cats.value||[]):[],vendors:vendors.status==='fulfilled'?(vendors.value.items||[]):[],products:products.status==='fulfilled'?(products.value.items||[]):[]}))},[]);const check=/** Handles check for the VSN Ecommerce interface. */ async()=>{if(apiBackend!=='laravel'){const r=s.checkIn();toast(r.msg,{tone:'success'});return;}try{const r=await lw.checkIn();toast(`+${r.totalRewardCoins} coins claimed`,{tone:'success',title:'Daily reward claimed'})}catch(e){toast(e.message,{tone:'danger'})}};return <><SEO title="VSN Ecommerce | Pakistan Online Shopping" description="Shop verified products, deals, rewards, Game Win and flexible payment options on VSN Ecommerce."/>
<section className="market-hero"><div className="hero-main"><div className="hero-copy"><span className="eyebrow">VSN MEGA DEAL DAYS</span><h1>Big marketplace choice. Less shopping friction.</h1><p>Verified sellers, clearer pricing, tracked delivery, flexible payments and rewards—all in one place.</p><div className="hero-actions"><Link className="ui-btn ui-btn--primary" to="/deals">Shop all deals</Link><Link className="ui-btn ui-btn--secondary" to="/games">Explore Game Win</Link></div><div className="hero-trust"><span><FaShieldAlt/>Verified sellers</span><span><FaTruck/>Tracked delivery</span><span><FaUndo/>Easy returns</span></div></div><SafeImage className="hero-main-image" src="https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1400&h=900&fit=crop" alt="VSN shopping deals"/></div><div className="hero-rail"><Card className="rail-deal"><span><FaBolt/> FLASH DEAL</span><b>Up to 35% off electronics</b><Link to="/search">Shop now <FaArrowRight/></Link></Card><Card className="rail-game"><span><FaGamepad/> LIVE GAME</span><b>{liveGames[0]?.name||'Game Win'}</b>{liveGames[0]&&<Countdown target={liveGames[0].announcementAt}/>}<Link to="/games">View entry</Link></Card></div></section>
<section className="home-section home-shortcuts"><div className="shortcut-grid"><Link to="/orders"><b>Track your orders</b><span>Delivery, returns & invoices</span></Link><Link to="/coins"><b>{walletCoins.toLocaleString()} VSN Coins</b><span>Worth Rs. {Number(walletValue).toFixed(2)}</span></Link><button onClick={check}><b>Daily free coins</b><span>Tap to check in today</span></button><Link to="/gifts"><b>Send a gift</b><span>Products or VSN Coins</span></Link><Link to="/affiliate"><b>Affiliate earnings</b><span>10-level referral network</span></Link></div></section>
<section className="home-section"><SectionHeader title="Shop by department" sub="Popular marketplace categories" action="See all" to="/search"/><div className="department-grid">{(apiBackend==='laravel'?market.categories:categories.map(/** Converts legacy category names only for non-Laravel fallback mode. */ name=>({name,slug:name,productsCount:null}))).map(/** Renders one real marketplace department. */ c=><Link key={c.slug||c.name} to={`/search?category=${encodeURIComponent(c.slug||c.name)}`}><span className="department-icon">{iconMap[c.name]||<FaStore/>}</span><b>{c.name}</b><small>{c.productsCount==null?'Browse products':`${Number(c.productsCount).toLocaleString()} items`}</small></Link>)}</div></section>
<section className="home-section deal-zone"><SectionHeader title="Today's deals" sub="Live server-authoritative marketplace promotions" action="View all deals" to="/deals"/><div className="product-grid commerce-dense">{(apiBackend==='laravel'?(dealItems.length?dealItems.map(/** Maps active server deals into product-card data. */ x=>{const p=normalizeLaravelProduct(x.product);return {...p,price:Math.round(Number(x.dealPriceMinor||0)/100),old:Math.round(Number(x.product?.priceMinor||0)/100)}}):market.products.slice(0,4).map(/** Uses real popular products when no deal is active. */ normalizeLaravelProduct)):products.slice(0,4).map(decorateGameProduct)).map(/** Renders one deal or popular-product card. */ p=><ProductCard key={p.publicId||p.id} product={p} onAdd={onAdd}/>)}</div></section>
<section className="home-section marketplace-panels"><Card className="promo-panel promo-coins"><FaCoins/><div><small>VSN REWARDS</small><h2>Earn on shopping. Spend almost anywhere.</h2><p>Use coins for products, Game Win entries and gifts. Buy coins or collect daily free coins.</p><Link to="/coins">Open coin wallet <FaArrowRight/></Link></div></Card><Card className="promo-panel promo-affiliate"><FaGift/><div><small>AFFILIATE NETWORK</small><h2>Referral rewards up to 10 levels deep.</h2><p>Earn coin commissions from qualified spending across your referral network.</p><Link to="/affiliate">View affiliate dashboard <FaArrowRight/></Link></div></Card></section>
<section className="home-section"><SectionHeader title="Recommended for you" sub={apiBackend==='laravel'?"Personalized from your marketplace activity":"Marketplace picks based on popular activity"}/><div className="product-grid commerce-dense">{(apiBackend==='laravel'?(personal.recommended.length?personal.recommended.map(/** Maps personalized server recommendations. */ x=>normalizeLaravelProduct(x.product)):market.products.slice(4,12).map(/** Uses real marketplace products when personalization has no rows. */ normalizeLaravelProduct)):products.slice(4).map(decorateGameProduct)).map(/** Renders one recommended marketplace product. */ p=><ProductCard key={p.id} product={p} onAdd={onAdd}/>)}</div></section>{apiBackend==='laravel'&&personal.recent.length>0&&<section className="home-section"><SectionHeader title="Recently viewed" sub="Continue where you left off" action="View history" to="/recently-viewed"/><div className="product-grid commerce-dense">{personal.recent.map(/** Inline callback for this operation. */ x=><ProductCard key={x.product.id} product={normalizeLaravelProduct(x.product)} onAdd={onAdd}/>)}</div></section>}{apiBackend==='laravel'&&personal.buyAgain.length>0&&<section className="home-section"><SectionHeader title="Buy again" sub="Real previous purchases at current price" action="View all" to="/buy-again"/><div className="product-grid commerce-dense">{personal.buyAgain.filter(/** Inline callback for this operation. */ x=>x.available).map(/** Inline callback for this operation. */ x=><ProductCard key={`${x.product.id}-${x.variantId||0}`} product={normalizeLaravelProduct(x.product)} onAdd={onAdd}/>)}</div></section>}
<section className="game-market-band"><div className='game-market-content'><span className="eyebrow">WIN FOR RS.1</span><h2>Game-enabled products with transparent announcement times.</h2><p>Each valid entry costs 70 coins. Winner announcements are scheduled and visible before entry.</p></div><div className="game-band-items">{liveGames.slice(0,3).map(/** Inline callback for this operation. */ g=><Link to="/games" key={g.id}><SafeImage src={g.image} alt={g.name}/><span><b>{g.name}</b><Countdown target={g.announcementAt}/></span></Link>)}</div></section>
<section className="home-section"><SectionHeader title="Marketplace stores" sub="Active public sellers from the live marketplace" action="View all stores" to="/vendors"/><div className="store-grid">{(apiBackend==='laravel'?market.vendors.slice(0,4):[]).map(/** Renders a public vendor returned by the live directory API. */ vendor=><Card key={vendor.id}><span className="store-logo">{vendor.logoUrl?<SafeImage src={vendor.logoUrl} alt={vendor.name}/>:vendor.name.split(' ').map(/** Builds initials when a seller has no logo. */ x=>x[0]).join('').slice(0,2)}</span><div><b>{vendor.name}</b><small><FaStore/> {Number(vendor.productsCount||0).toLocaleString()} published products</small></div><Link to={vendor.shopUrl}>Visit store</Link></Card>)}</div>{apiBackend==='laravel'&&!market.vendors.length&&<Card><p>No public seller storefronts are available yet.</p></Card>}</section>
</>}
