import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import SEO from '../components/SEO';
import ProductCard from '../components/ProductCard';
import {Button,Card,SectionHeader,Status} from '../components/Toolkit';
import {clearRecentlyViewed,getBuyAgain,getRecentlyViewed,getWishlist,removeWishlist} from '../platform/personalization';
import {normalizeLaravelProduct} from '../platform/catalog';
/** Handles page for the VSN Ecommerce interface. */
function Page({title,sub,children}){return <><SEO title={`${title} | VSN Ecommerce`} description={sub}/><div className="simple-page"><div className="page-title"><h1>{title}</h1><p>{sub}</p></div>{children}</div></>}
/** Handles wishlist page for the VSN Ecommerce interface. */
export function WishlistPage({onAdd}){const [data,setData]=useState(null),[error,setError]=useState('');const load=/** Handles load for the VSN Ecommerce interface. */ ()=>getWishlist().then(setData).catch(/** Inline callback for this operation. */ e=>setError(e.message));useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);const del=/** Handles del for the VSN Ecommerce interface. */ async id=>{try{await removeWishlist(id);await load()}catch(e){setError(e.message)}};return <Page title="Wishlist" sub="Products you saved to revisit later.">{error&&<Status>{error}</Status>}<div className="product-grid commerce-dense">{data?.items?.map(/** Inline callback for this operation. */ row=>{const p={...normalizeLaravelProduct(row.product),selectedVariantId:row.variantId||null,inStock:row.variantId?Boolean(row.available):normalizeLaravelProduct(row.product).inStock};return <div className="personalized-product" key={row.id}><ProductCard product={p} onAdd={onAdd}/><Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>del(row.id)}>Remove</Button></div>})}</div>{data&&!data.items?.length&&<Card><p>Your wishlist is empty.</p><Link to="/search">Explore products</Link></Card>}</Page>}
/** Handles recently viewed page for the VSN Ecommerce interface. */
export function RecentlyViewedPage({onAdd}){const [rows,setRows]=useState(null),[error,setError]=useState('');useEffect(/** Inline callback for this operation. */ ()=>{getRecentlyViewed(30).then(/** Inline callback for this operation. */ d=>setRows(d.items||[])).catch(/** Inline callback for this operation. */ e=>setError(e.message))},[]);const clear=/** Handles clear for the VSN Ecommerce interface. */ async()=>{try{await clearRecentlyViewed();setRows([])}catch(e){setError(e.message)}};return <Page title="Recently viewed" sub="Products from your signed-in browsing history.">{error&&<Status>{error}</Status>}{rows?.length>0&&<div style={{display:'flex',justifyContent:'flex-end',marginBottom:12}}><Button variant="secondary" onClick={clear}>Clear history</Button></div>}<div className="product-grid commerce-dense">{rows?.map(/** Inline callback for this operation. */ row=><ProductCard key={`${row.product.id}-${row.viewedAt}`} product={normalizeLaravelProduct(row.product)} onAdd={onAdd}/>)}</div>{rows&&!rows.length&&<Card><p>No recent products yet.</p></Card>}</Page>}
/** Handles buy again page for the VSN Ecommerce interface. */
export function BuyAgainPage({onAdd}){const [rows,setRows]=useState(null),[error,setError]=useState('');useEffect(/** Inline callback for this operation. */ ()=>{getBuyAgain(30).then(/** Inline callback for this operation. */ d=>setRows(d.items||[])).catch(/** Inline callback for this operation. */ e=>setError(e.message))},[]);return <Page title="Buy again" sub="Reorder from real previous purchases using current price and stock.">{error&&<Status>{error}</Status>}<div className="product-grid commerce-dense">{rows?.map(/** Inline callback for this operation. */ row=><div className="personalized-product" key={`${row.product.id}-${row.variantId||0}`}><ProductCard product={{...normalizeLaravelProduct(row.product),selectedVariantId:row.variantId||null,inStock:Boolean(row.available)}} onAdd={onAdd}/><small>Last purchased {row.lastPurchasedAt?new Date(row.lastPurchasedAt).toLocaleDateString():''}{!row.available?' · currently unavailable':''}</small></div>)}</div>{rows&&!rows.length&&<Card><p>No eligible previous purchases yet.</p></Card>}</Page>}
