import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import SEO from '../components/SEO';
import {Badge,Button,Card,SectionHeader,Status} from '../components/Toolkit';
import {apiGet,apiPost} from '../platform/api';
import {FaShieldAlt,FaLink,FaDatabase,FaServer,FaCheckCircle,FaExclamationTriangle} from 'react-icons/fa';

/** Handles production readiness for the VSN Ecommerce interface. */
export default function ProductionReadiness(){
 return <LaravelProductionReadiness/>;
}

/** Handles laravel production readiness for the VSN Ecommerce interface. */
function LaravelProductionReadiness(){
 const [data,setData]=useState(null),[providerData,setProviderData]=useState({providers:[],reconciliations:[]}),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=/** Handles load for the VSN Ecommerce interface. */ ()=>Promise.all([apiGet('/admin/system/launch-gate'),apiGet('/admin/system/providers')]).then(/** Inline callback for this operation. */ ([gate,providers])=>{setData(gate);setProviderData(providers||{providers:[],reconciliations:[]});setError('')}).catch(/** Inline callback for this operation. */ e=>setError(e.message));
 useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);
 const run=/** Handles run for the VSN Ecommerce interface. */ async()=>{setBusy('gate');setError('');try{await apiPost('/admin/system/launch-gate',{});await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const probe=/** Handles probe for the VSN Ecommerce interface. */ async()=>{setBusy('probe');setError('');try{await apiPost('/admin/system/providers/probe',{});await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const reconcile=/** Handles reconcile for the VSN Ecommerce interface. */ async(p)=>{setBusy(`reconcile-${p.type}-${p.code}`);setError('');try{await apiPost('/admin/system/providers/reconcile',{type:p.type,code:p.code});await load()}catch(e){setError(e.message)}finally{setBusy('')}};
 const report=data?.current; const checks=report?.checks||[];
 const pass=checks.filter(/** Inline callback for this operation. */ x=>x.status==='pass').length, warnings=checks.filter(/** Inline callback for this operation. */ x=>x.status==='warning').length, blockers=checks.filter(/** Inline callback for this operation. */ x=>x.status==='block').length;
 const reconcilable=new Set(['payment','shipping','kyc']);
 return <><SEO title="Production Readiness | VSN Ecommerce" description="Machine-verifiable Laravel launch gates, live provider health and reconciliation evidence."/><div className="page-wrap production-readiness"><SectionHeader eyebrow="ADMIN / LAUNCH GATE" title="Production readiness" description="Runtime blockers plus live provider health and reconciliation evidence. Credentials alone never mark a provider launch-ready."/>{error&&<Status>{error}</Status>}{!report?<Card><p>Loading launch gates…</p></Card>:<><div className="readiness-summary"><Card><FaCheckCircle/><small>Passing checks</small><strong>{pass}</strong><span>Automated gates currently passing</span></Card><Card><FaExclamationTriangle/><small>Warnings</small><strong>{warnings}</strong><span>Review before launch</span></Card><Card><FaShieldAlt/><small>Blocking gates</small><strong>{blockers}</strong><span>{report.ready?'No automated blocker':'Launch remains blocked'}</span></Card><Card><FaServer/><small>Release</small><strong>{report.release||'unknown'}</strong><span>{report.environment} · checked {new Date(report.checkedAt).toLocaleString()}</span></Card></div>
 <Card className="system-section"><div className="readiness-title"><div><h2>Automated launch gate</h2><p>Production stays blocked until blocking checks are zero.</p></div><Button onClick={run} disabled={!!busy}>{busy==='gate'?'Running…':'Run launch gate'}</Button></div><div className="status-stack">{checks.map(/** Inline callback for this operation. */ c=><Status key={c.code} ok={c.status==='pass'}><b>{c.code.replaceAll('_',' ')}</b> · {c.status.toUpperCase()} · {c.message}</Status>)}</div></Card>
 <Card className="system-section"><div className="readiness-title"><div><h2>Live provider health</h2><p>Active probes test the configured payment, vault, courier, SMS, email and KYC provider contracts.</p></div><Button variant="secondary" onClick={probe} disabled={!!busy}>{busy==='probe'?'Probing…':'Probe providers'}</Button></div><div className="simple-list">{(providerData.providers||[]).length?(providerData.providers||[]).map(/** Inline callback for this operation. */ p=><div key={`${p.type}-${p.code}`}><FaLink/><span><b>{p.type.replaceAll('_',' ')} · {p.code}</b><small>{p.message} · {p.latencyMs??0} ms · {p.checkedAt?new Date(p.checkedAt).toLocaleString():'never'}</small></span><span><Badge tone={p.status==='healthy'&&p.productionReady?'success':'warning'}>{p.status}</Badge>{reconcilable.has(p.type)&&<>{' '}<Button variant="secondary" disabled={!!busy} onClick={/** Inline callback for this operation. */ ()=>reconcile(p)}>{busy===`reconcile-${p.type}-${p.code}`?'Checking…':'Reconcile'}</Button></>}</span></div>):<p>No provider probes have been persisted yet.</p>}</div></Card>
 <Card className="system-section"><h2>Recent provider reconciliations</h2><div className="simple-list">{(providerData.reconciliations||[]).length?(providerData.reconciliations||[]).slice(0,12).map(/** Inline callback for this operation. */ r=><div key={r.id}><FaDatabase/><span><b>{r.type} · {r.code}</b><small>{r.checked} checked · {r.mismatches} mismatches · {r.errors} errors · {r.completedAt?new Date(r.completedAt).toLocaleString():'running'}</small></span><Badge tone={r.status==='completed'?'success':'warning'}>{r.status}</Badge></div>):<p>No reconciliation evidence yet.</p>}</div></Card>
 <div className="two-col system-section"><Card><h2>Latest persisted run</h2>{data.latest?<div className="simple-list"><div><FaShieldAlt/><span><b>{data.latest.status}</b><small>{data.latest.blockersCount} blocker(s) · {data.latest.warningsCount} warning(s) · {new Date(data.latest.ranAt).toLocaleString()}</small></span></div></div>:<p>No persisted launch-gate run yet.</p>}</Card><Card><h2>Operations shortcuts</h2><div className="action-list"><Link to="/admin/operations">System health & finance</Link><Link to="/admin/risk">Risk & abuse</Link><Link to="/admin/analytics">Analytics & reports</Link><Link to="/admin/acceptance">Final production acceptance</Link><Link to="/legal">Legal & compliance center</Link></div></Card></div></>}</div></>;
}

/** Handles legal center for the VSN Ecommerce interface. */
export function LegalCenter(){
 const docs=['Terms of Service','Privacy Policy','Returns & Refunds Policy','Seller Marketplace Terms','Game Win Rules','Affiliate Program Rules','VSN Coins Terms','KYC & Identity Consent'];
 return <><SEO title="Legal & Compliance | VSN Ecommerce" description="Marketplace terms, privacy, returns, rewards, game and identity policies."/><div className="page-wrap"><SectionHeader eyebrow="TRUST & COMPLIANCE" title="Legal & compliance center" description="Policy surfaces required before public launch. Replace draft text with counsel-approved jurisdiction-specific wording."/><div className="legal-grid">{docs.map(/** Inline callback for this operation. */ (d,i)=><Card key={d}><Badge tone={i<3?'primary':'neutral'}>{i<3?'Core policy':'Special program'}</Badge><h3>{d}</h3><p>Versioned policy document with acceptance timestamp, country scope and audit history.</p><Button variant="secondary">Review draft</Button></Card>)}</div><Card className="system-section"><h2>Consent requirements</h2><p>Checkout, KYC, affiliate enrollment, coin purchase/transfer and paid Game Win entry should each store explicit policy version + timestamp + user + IP/device hash where legally appropriate.</p></Card></div></>;
}
