import {useEffect,useState} from 'react';
import SEO from '../components/SEO';
import StripeCardSetup from '../components/StripeCardSetup';import {Card,Field,Select,Button,Status,Badge} from '../components/Toolkit';import {apiDelete,apiGet,apiPost,apiPut} from '../platform/api';
/** Handles profile for the VSN Ecommerce interface. */
export default function Profile(){return <LaravelProfile/>}
/** Handles laravel profile for the VSN Ecommerce interface. */
function LaravelProfile(){
 const[user,setUser]=useState(null),[kyc,setKyc]=useState({items:[]}),[security,setSecurity]=useState({devices:[],events:[]}),[payments,setPayments]=useState({items:[],security:{}}),[phone,setPhone]=useState(''),[code,setCode]=useState(''),[sandboxCode,setSandboxCode]=useState(''),[idType,setIdType]=useState('CNIC'),[idNumber,setIdNumber]=useState(''),[idFront,setIdFront]=useState(null),[proof,setProof]=useState(null),[brand,setBrand]=useState('visa'),[last4,setLast4]=useState('4242'),[expMonth,setExpMonth]=useState('12'),[expYear,setExpYear]=useState(String(new Date().getFullYear()+2)),[holder,setHolder]=useState(''),[msg,setMsg]=useState('');
 const load=/** Handles load for the VSN Ecommerce interface. */ ()=>Promise.all([apiGet('/profile'),apiGet('/kyc'),apiGet('/security'),apiGet('/payment-methods')]).then(/** Inline callback for this operation. */ ([u,k,s,p])=>{setUser(u);setKyc(k);setSecurity(s);setPayments(p);setPhone(u.profile?.phone||'')}).catch(/** Inline callback for this operation. */ e=>setMsg(e.message));useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);
 const stepUp=/** Handles step up for the VSN Ecommerce interface. */ async()=>{const password=prompt('Confirm your current password to change saved payment methods.');if(!password)throw new Error('Password confirmation cancelled.');return apiPost('/security/step-up',{password,purpose:'payment_methods'});};
 const phoneSend=/** Handles phone send for the VSN Ecommerce interface. */ async()=>{try{const d=await apiPost('/profile/phone/send-code',{phone});setSandboxCode(d.sandboxCode||'');setMsg(d.sandboxCode?`Sandbox code: ${d.sandboxCode}`:'Verification code sent.')}catch(e){setMsg(e.message)}};const phoneVerify=/** Handles phone verify for the VSN Ecommerce interface. */ async()=>{try{await apiPost('/profile/phone/verify',{phone,code});setMsg('Phone verified.');load()}catch(e){setMsg(e.message)}};
 const submitId=/** Handles submit id for the VSN Ecommerce interface. */ async()=>{const f=new FormData();f.append('type','government_id');f.append('document_number',idNumber);f.append('country_code','PK');if(idFront)f.append('document_front',idFront);try{await apiPost('/kyc',f);setMsg('Government ID submitted for review.');load()}catch(e){setMsg(e.message)}};const submitProof=/** Handles submit proof for the VSN Ecommerce interface. */ async()=>{const f=new FormData();f.append('type','address_proof');if(proof)f.append('address_proof',proof);try{await apiPost('/kyc',f);setMsg('Address proof submitted for review.');load()}catch(e){setMsg(e.message)}};
 const addSandboxMethod=/** Handles add sandbox method for the VSN Ecommerce interface. */ async()=>{try{const setup=await apiPost('/payment-methods/sandbox/setup',{brand,last4,expMonth:Number(expMonth),expYear:Number(expYear),holderName:holder||null});const auth=await stepUp();await apiPost('/payment-methods',{provider:setup.provider,providerToken:setup.providerToken,makeDefault:payments.items.length===0},{headers:{'X-Step-Up-Token':auth.token}});setMsg('Tokenized sandbox payment method saved. No card number or CVC was stored.');load()}catch(e){setMsg(e.message)}};
 const defaultMethod=/** Handles default method for the VSN Ecommerce interface. */ async(id)=>{try{const auth=await stepUp();await apiPost(`/payment-methods/${id}/default`,{}, {headers:{'X-Step-Up-Token':auth.token}});setMsg('Default payment method updated.');load()}catch(e){setMsg(e.message)}};
 const removeMethod=/** Handles remove method for the VSN Ecommerce interface. */ async(id)=>{try{const auth=await stepUp();await apiDelete(`/payment-methods/${id}`,{headers:{'X-Step-Up-Token':auth.token}});setMsg('Saved payment method revoked.');load()}catch(e){setMsg(e.message)}};
 const latest=/** Handles latest for the VSN Ecommerce interface. */ t=>kyc.items?.find(/** Inline callback for this operation. */ x=>x.type===t);if(!user)return <div className="page"><Card><p>{msg||'Loading profile…'}</p></Card></div>;
 return <><SEO title="Profile & Verification | VSN Ecommerce"/><div className="page"><div className="page-head"><h1>Profile & verification</h1><p>Identity, payment vault controls and device security are server-authoritative.</p></div>{msg&&<Status>{msg}</Status>}
 <div className="two-col"><Card><h2>Basic information</h2><Field label="Full name" value={user.name||''} onChange={/** Inline callback for this operation. */ e=>setUser({...user,name:e.target.value})}/><Field label="Email" value={user.email||''} disabled/><Button onClick={/** Inline callback for this operation. */ async()=>{try{const d=await apiPut('/profile',{name:user.name});setUser(d);setMsg('Profile saved.')}catch(e){setMsg(e.message)}}}>Save</Button></Card><Card><h2>Phone verification</h2><Status ok={!!user.verification?.phoneVerified}>{user.verification?.phoneVerified?'Verified':'Required'}</Status><Field label="Phone" value={phone} onChange={/** Inline callback for this operation. */ e=>setPhone(e.target.value)}/><Button onClick={phoneSend}>Send OTP</Button><Field label="Verification code" value={code} onChange={/** Inline callback for this operation. */ e=>setCode(e.target.value)} help={sandboxCode?'Local sandbox code shown above':''}/><Button onClick={phoneVerify}>Verify phone</Button></Card></div>
 <Card><h2>Saved payment methods</h2><p>Provider-issued tokens only. VSN never stores PAN/card number or CVC.</p>{payments.items?.length?payments.items.map(/** Inline callback for this operation. */ m=><div className="switch-row" key={m.id}><span><b>{(m.brand||'Card').toUpperCase()} •••• {m.last4} {m.default&&<Badge tone="success">Default</Badge>}</b><small>{m.provider} · expires {String(m.expiry?.month||'--').padStart(2,'0')}/{m.expiry?.year||'----'} · {m.status}</small></span><div>{!m.default&&<Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>defaultMethod(m.id)}>Make default</Button>} <Button variant="secondary" onClick={/** Inline callback for this operation. */ ()=>removeMethod(m.id)}>Remove</Button></div></div>):<p>No saved payment methods.</p>}
 {payments.security?.browserSetupProvider==='stripe'&&<StripeCardSetup stepUp={stepUp} makeDefault={!payments.items?.length} onSaved={/** Inline callback for this operation. */ ()=>{setMsg('Stripe payment method saved.');load()}}/>}
 {payments.security?.sandboxSetupEnabled&&<div><h3>Add local sandbox token</h3><p>This simulator asks only for masked test metadata; never enter a real card number.</p><div className="two-col"><Select label="Brand" value={brand} onChange={/** Inline callback for this operation. */ e=>setBrand(e.target.value)}><option value="visa">Visa</option><option value="mastercard">Mastercard</option><option value="amex">Amex</option></Select><Field label="Last 4 test digits" value={last4} maxLength="4" onChange={/** Inline callback for this operation. */ e=>setLast4(e.target.value.replace(/\D/g,'').slice(0,4))}/><Field label="Expiry month" type="number" min="1" max="12" value={expMonth} onChange={/** Inline callback for this operation. */ e=>setExpMonth(e.target.value)}/><Field label="Expiry year" type="number" min={new Date().getFullYear()} value={expYear} onChange={/** Inline callback for this operation. */ e=>setExpYear(e.target.value)}/></div><Field label="Cardholder test label" value={holder} onChange={/** Inline callback for this operation. */ e=>setHolder(e.target.value)}/><Button onClick={addSandboxMethod}>Create & save sandbox token</Button></div>}</Card>
 <div className="two-col"><Card><h2>Government ID</h2><Status ok={latest('government_id')?.status==='approved'}>{latest('government_id')?.status||'Not submitted'}</Status><Select label="ID type" value={idType} onChange={/** Inline callback for this operation. */ e=>setIdType(e.target.value)}><option>CNIC</option><option>Passport</option><option>National ID</option></Select><Field label="ID number" value={idNumber} onChange={/** Inline callback for this operation. */ e=>setIdNumber(e.target.value)}/><label className="upload-box">Upload ID front<input type="file" accept="image/*,.pdf" onChange={/** Inline callback for this operation. */ e=>setIdFront(e.target.files?.[0]||null)}/><span>{idFront?.name||'Private JPG/PNG/WebP/PDF'}</span></label><Button disabled={latest('government_id')?.status==='pending'||latest('government_id')?.status==='approved'} onClick={submitId}>Submit verification</Button>{latest('government_id')?.rejectionReason&&<p>{latest('government_id').rejectionReason}</p>}</Card><Card><h2>Address proof</h2><Status ok={latest('address_proof')?.status==='approved'}>{latest('address_proof')?.status||'Not submitted'}</Status><label className="upload-box">Utility bill / bank statement / government document<input type="file" accept="image/*,.pdf" onChange={/** Inline callback for this operation. */ e=>setProof(e.target.files?.[0]||null)}/><span>{proof?.name||'Private document'}</span></label><Button disabled={latest('address_proof')?.status==='pending'||latest('address_proof')?.status==='approved'} onClick={submitProof}>Submit proof</Button></Card></div>
 <Card><h2>Devices & sessions</h2>{security.devices?.map(/** Inline callback for this operation. */ d=><div className="switch-row" key={d.id}><span><b>{d.label}{d.current?' · Current':''}</b><small>{d.lastIp||'—'} · {d.lastSeenAt?new Date(d.lastSeenAt).toLocaleString():''}</small></span><div>{d.trusted&&<Status ok>Trusted</Status>}{!d.current&&<Button variant="secondary" onClick={/** Inline callback for this operation. */ async()=>{await apiPost(`/security/devices/${d.id}/revoke`,{});load()}}>Revoke</Button>}</div></div>)}</Card><Card><h2>Recent security activity</h2>{security.events?.slice(0,20).map(/** Inline callback for this operation. */ e=><div className="switch-row" key={e.id}><span><b>{e.type}</b><small>{e.ip||'—'} · {e.createdAt?new Date(e.createdAt).toLocaleString():''}</small></span><span>{e.severity}</span></div>)}</Card></div></>}

