import {useEffect,useState} from "react";
import SEO from "../components/SEO";
import {Badge,Button,Card,Field,Select,Status} from "../components/Toolkit";
import {apiGet,apiPost} from "../platform/api";

const tone=/** Handles tone for the VSN Ecommerce interface. */ (level)=>level==="critical"?"danger":level==="high"?"warning":level==="medium"?"primary":"success";
/** Handles admin risk for the VSN Ecommerce interface. */
export default function AdminRisk(){
  const [data,setData]=useState(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
  const [hold,setHold]=useState({userId:"",vendorId:"",scope:"payments",reason:"",expiresAt:""});
  const load=/** Handles load for the VSN Ecommerce interface. */ ()=>apiGet('/admin/risk').then(setData).catch(/** Inline callback for this operation. */ e=>setMsg(e.message));
  useEffect(/** Inline callback for this operation. */ ()=>{load()},[]);
  const run=/** Handles run for the VSN Ecommerce interface. */ async(fn)=>{setBusy(true);setMsg("");try{await fn();setMsg("Risk control updated.");await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}};
  const createHold=/** Handles create hold for the VSN Ecommerce interface. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost('/admin/risk/holds',{userId:hold.userId?Number(hold.userId):null,vendorId:hold.vendorId?Number(hold.vendorId):null,scope:hold.scope,reason:hold.reason,expiresAt:hold.expiresAt||null}));
  return <><SEO title="Risk Center | VSN Ecommerce"/><main className="content-page"><h1>Risk & Abuse Center</h1><p>Evidence-based fraud review, scoped holds and velocity-control monitoring. Automated scores open review cases; they do not permanently ban accounts by themselves.</p>{msg&&<Status>{msg}</Status>}
    <div className="metric-grid"><Card><small>Open cases</small><strong>{data?.summary?.openCases??0}</strong></Card><Card><small>Active holds</small><strong>{data?.summary?.activeHolds??0}</strong></Card><Card><small>High-risk users</small><strong>{data?.summary?.highRiskUsers??0}</strong></Card><Card><small>High-risk sellers</small><strong>{data?.summary?.highRiskVendors??0}</strong></Card></div>
    <Card><h2>Controls</h2><p>Mode: <Badge>{data?.mode||'observe'}</Badge> · Review score {data?.reviewScore??50} · Critical score {data?.criticalScore??75} · Auto-hold critical: {data?.autoHoldCritical?'enabled':'off'}</p><div className="form-grid"><Field label="User numeric ID" value={hold.userId} onChange={/** Inline callback for this operation. */ e=>setHold({...hold,userId:e.target.value,vendorId:""})}/><Field label="Vendor numeric ID" value={hold.vendorId} onChange={/** Inline callback for this operation. */ e=>setHold({...hold,vendorId:e.target.value,userId:""})}/><Select label="Hold scope" value={hold.scope} onChange={/** Inline callback for this operation. */ e=>setHold({...hold,scope:e.target.value})}><option value="payments">Payments / checkout</option><option value="wallet">Wallet transfers</option><option value="games">Game Win</option><option value="returns">Returns</option><option value="affiliate">Affiliate rewards</option><option value="payouts">Seller payouts</option><option value="all">All sensitive actions</option></Select><Field label="Expires at (optional ISO/date)" value={hold.expiresAt} onChange={/** Inline callback for this operation. */ e=>setHold({...hold,expiresAt:e.target.value})}/><Field label="Reason" value={hold.reason} onChange={/** Inline callback for this operation. */ e=>setHold({...hold,reason:e.target.value})}/></div><Button disabled={busy||(!hold.userId&&!hold.vendorId)||hold.reason.length<5} onClick={createHold}>Create scoped hold</Button></Card>
    <Card><h2>Highest risk profiles</h2><div className="simple-list">{data?.profiles?.map(/** Inline callback for this operation. */ p=><div key={p.id}><span><b>{p.user?.email||p.vendor?.name||p.id}</b><small>{Object.entries(p.signals||{}).map(/** Inline callback for this operation. */ ([k,v])=>`${k}: ${typeof v?.value==='object'?JSON.stringify(v.value):v?.value}`).join(' · ')||'No active signals'}</small></span><span><Badge tone={tone(p.level)}>{p.level}</Badge> <strong>{p.score}/100</strong> {p.user&&<Button variant="secondary" disabled={busy} onClick={/** Inline callback for this operation. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost(`/admin/risk/users/${p.user.id}/evaluate`,{}))}>Re-evaluate</Button>} {p.vendor&&<Button variant="secondary" disabled={busy} onClick={/** Inline callback for this operation. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost(`/admin/risk/vendors/${p.vendor.id}/evaluate`,{}))}>Re-evaluate</Button>}</span></div>)}</div></Card>
    <div className="two-col"><Card><h2>Open cases</h2>{data?.cases?.length?data.cases.map(/** Inline callback for this operation. */ c=><div className="switch-row" key={c.id}><span><b>{c.title}</b><small>{c.user?.email||c.vendor?.name} · score {c.scoreAtOpen} · {c.priority}</small></span><div><Button variant="secondary" disabled={busy} onClick={/** Inline callback for this operation. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost(`/admin/risk/cases/${c.id}/status`,{status:'reviewing'}))}>Review</Button> <Button disabled={busy} onClick={/** Inline callback for this operation. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost(`/admin/risk/cases/${c.id}/status`,{status:'resolved',resolution:'Reviewed and resolved by risk operations.'}))}>Resolve</Button></div></div>):<p>No open cases.</p>}</Card><Card><h2>Active holds</h2>{data?.holds?.length?data.holds.map(/** Inline callback for this operation. */ h=><div className="switch-row" key={h.id}><span><b>{h.scope} · {h.user?.email||h.vendor?.name}</b><small>{h.reason}{h.expiresAt?` · expires ${new Date(h.expiresAt).toLocaleString()}`:''}</small></span><Button variant="secondary" disabled={busy} onClick={/** Inline callback for this operation. */ ()=>run(/** Inline callback for this operation. */ ()=>apiPost(`/admin/risk/holds/${h.id}/release`,{note:'Released after manual review.'}))}>Release</Button></div>):<p>No active holds.</p>}</Card></div>
    <Card><h2>Recent immutable evidence</h2><div className="simple-list">{data?.recentEvents?.map(/** Inline callback for this operation. */ e=><div key={e.id}><span><b>{e.type}</b><small>{e.user||e.vendor||'system'} · {e.scope||'general'} · {new Date(e.occurredAt).toLocaleString()}</small></span><Badge tone={tone(e.severity)}>{e.severity}</Badge></div>)}</div></Card>
  </main></>;
}
