import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {FaSearch,FaStore} from 'react-icons/fa';
import SEO from '../components/SEO';
import ProductCard from '../components/ProductCard';
import {Card,SafeImage,Status} from '../components/Toolkit';
import {apiGet} from '../platform/api';
import {normalizeLaravelProduct} from '../platform/catalog';

/** Lists all active public seller storefronts returned by Laravel. */
export function VendorsList(){const [items,setItems]=useState([]),[q,setQ]=useState(''),[error,setError]=useState('');useEffect(/** Loads the current public seller directory without stale-search races. */ ()=>{let live=true;setError('');const t=setTimeout(/** Debounces seller directory search. */ ()=>apiGet(`/vendors${q.trim()?`?q=${encodeURIComponent(q.trim())}`:''}`).then(/** Stores marketplace-safe seller cards only for the latest query. */ d=>{if(live)setItems(d.items||[])}).catch(/** Displays vendor-directory API failures only for the active query. */ e=>{if(live)setError(e.message)}),180);return/** Cancels a pending seller-directory search and ignores late responses. */ ()=>{live=false;clearTimeout(t)}},[q]);return <><SEO title="Stores | VSN Ecommerce"/><div className="simple-page vendor-directory-page"><div className="page-title"><span>MARKETPLACE STORES</span><h1>All sellers</h1><p>Browse active seller storefronts and their published products.</p></div>{error&&<Status>{error}</Status>}<div className="vendor-directory-search"><FaSearch/><input value={q} onChange={/** Updates vendor search text. */ e=>setQ(e.target.value)} placeholder="Search stores"/></div><div className="vendor-directory-grid">{items.map(/** Renders one public seller storefront card. */ vendor=><Link key={vendor.id} className="vendor-directory-card" to={vendor.shopUrl}><div className="vendor-directory-logo">{vendor.logoUrl?<SafeImage src={vendor.logoUrl} alt={vendor.name}/>:<FaStore/>}</div><div><h3>{vendor.name}</h3><p>{vendor.headline||vendor.description||'Marketplace seller'}</p><small>{vendor.productsCount} published product{vendor.productsCount===1?'':'s'}</small></div></Link>)}</div>{!items.length&&!error&&<Card><p>No active storefronts found.</p></Card>}</div></>}

/** Renders one seller's public storefront using only that seller's published catalog. */
export function VendorShop({onAdd}){const {slug}=useParams();const [data,setData]=useState(null),[error,setError]=useState('');useEffect(/** Loads the seller storefront and ignores late responses after a slug change. */ ()=>{let live=true;setData(null);setError('');apiGet(`/vendors/${encodeURIComponent(slug)}`).then(/** Stores the active seller storefront response. */ row=>{if(live)setData(row)}).catch(/** Displays public storefront API failures for the active route only. */ e=>{if(live)setError(e.message)});return/** Prevents an obsolete storefront response from replacing the current route. */ ()=>{live=false}},[slug]);const vendor=data?.vendor;return <><SEO title={`${vendor?.name||'Store'} | VSN Ecommerce`} description={vendor?.description||vendor?.headline||'Seller storefront'}/><div className="simple-page vendor-shop-page">{error&&<Status>{error}</Status>}{vendor&&<><section className="vendor-shop-hero"><div className="vendor-shop-logo">{vendor.logoUrl?<SafeImage src={vendor.logoUrl} alt={vendor.name}/>:<FaStore/>}</div><div><span>VERIFIED MARKETPLACE STORE</span><h1>{vendor.name}</h1><p>{vendor.headline||vendor.description||'Browse this seller’s published catalog.'}</p>{vendor.supportEmail&&<small>Support: {vendor.supportEmail}</small>}</div></section><div className="section-title"><div><h2>Products</h2><p>{data.products?.length||0} published items from {vendor.name}</p></div></div><div className="product-grid commerce-dense">{(data.products||[]).map(/** Renders a seller product using the shared marketplace card. */ p=><ProductCard key={p.publicId||p.id} product={normalizeLaravelProduct(p)} onAdd={onAdd}/>)}</div>{!data.products?.length&&<Card><p>This store has no published products yet.</p></Card>}</>}</div></>}
