[program:vsn-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/vsn/current
command=php /var/www/vsn/current/artisan queue:work redis --queue=critical,maintenance,notifications,reports,default --sleep=1 --tries=5 --timeout=900 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=930
