<?php
namespace App\Domain\Tax\Services;
use App\Models\{CheckoutSession,CheckoutTaxLine,TaxClass,TaxRate,Vendor,VendorTaxProfile};
use Illuminate\Support\Collection;
/** Defines the CheckoutTaxCalculator class and its project responsibilities. */
class CheckoutTaxCalculator {
 /** Initializes the CheckoutTaxCalculator instance and its dependencies. */
 public function __construct(private readonly TaxJurisdictionResolver $jurisdictions){}
 /** Executes the checkout tax calculator operation. */
 public function execute(CheckoutSession $session):array {
  CheckoutTaxLine::query()->where('checkout_session_id',$session->id)->delete();$session->load(['items.product','items.vendor','promotionAllocations']);$jur=$this->jurisdictions->resolve($session->address_snapshot??[]); if(!$jur||!config('vsn.tax.enabled',false)){return $this->save($session,0,0,0,null);}
  $defaultClass=TaxClass::query()->where('status','active')->where('is_default',true)->first();$total=0;$included=0;$added=0;
  foreach($session->items as $item){$product=$item->product;if(!$product)continue;$profile=$this->profile($item->vendor);if($profile['mode']==='none')continue;$classId=$product->tax_class_id?:$defaultClass?->id;$rates=$this->rates($jur->id,$classId,'product');if($rates->isEmpty())continue;$discount=(int)$session->promotionAllocations->where('checkout_session_item_id',$item->id)->sum('discount_minor');$gross=max(0,(int)$item->line_total_minor-$discount);$inc=$product->price_includes_tax!==null?(bool)$product->price_includes_tax:(bool)$profile['includes'];$parts=$this->compute($gross,$rates,$inc);
   foreach($parts as $p){CheckoutTaxLine::create(['checkout_session_id'=>$session->id,'checkout_session_item_id'=>$item->id,'vendor_id'=>$item->vendor_id,'tax_jurisdiction_id'=>$jur->id,'tax_class_id'=>$classId,'tax_rate_id'=>$p['rate']->id,'source'=>'product','source_reference'=>'item:'.$item->id,'label'=>$p['rate']->label,'rate_bps'=>$p['rate']->rate_bps,'taxable_minor'=>$p['taxable'],'tax_minor'=>$p['tax'],'price_includes_tax'=>$inc,'liability_bearer'=>$profile['mode'],'metadata'=>['country'=>$jur->country_code,'region'=>$jur->region_code]]);$total+=$p['tax'];if($inc)$included+=$p['tax'];else $added+=$p['tax'];}
  }
  $groups=$session->items->groupBy(/** Inline callback for this operation. */ fn($i)=>(string)($i->vendor_id??0));$ship=$this->allocate((int)$session->shipping_minor,$groups->map(/** Inline callback for this operation. */ fn()=>1));
  foreach($groups as $key=>$items){$vendorId=((int)$key)?:null;$vendor=$vendorId?Vendor::query()->find($vendorId):null;$profile=$this->profile($vendor);if($profile['mode']==='none')continue;$rates=$this->rates($jur->id,null,'shipping');if($rates->isEmpty())continue;$amount=(int)($ship[$key]??0);$inc=(bool)config('vsn.tax.shipping_prices_include_tax',false);$parts=$this->compute($amount,$rates,$inc);foreach($parts as $p){CheckoutTaxLine::create(['checkout_session_id'=>$session->id,'checkout_session_item_id'=>null,'vendor_id'=>$vendorId,'tax_jurisdiction_id'=>$jur->id,'tax_class_id'=>null,'tax_rate_id'=>$p['rate']->id,'source'=>'shipping','source_reference'=>'shipping:vendor:'.$key,'label'=>$p['rate']->label,'rate_bps'=>$p['rate']->rate_bps,'taxable_minor'=>$p['taxable'],'tax_minor'=>$p['tax'],'price_includes_tax'=>$inc,'liability_bearer'=>$profile['mode'],'metadata'=>['country'=>$jur->country_code,'region'=>$jur->region_code]]);$total+=$p['tax'];if($inc)$included+=$p['tax'];else $added+=$p['tax'];}}
  return $this->save($session,$total,$included,$added,$jur);
 }
 /** Handles profile for the checkout tax calculator workflow. */
 private function profile(?Vendor $vendor):array { if(!$vendor)return ['mode'=>(string)config('vsn.tax.default_collection_mode','none'),'includes'=>(bool)config('vsn.tax.default_prices_include_tax',false)];$p=VendorTaxProfile::query()->where('vendor_id',$vendor->id)->where('status','active')->first(); if(!$p)return ['mode'=>(string)config('vsn.tax.default_collection_mode','none'),'includes'=>(bool)config('vsn.tax.default_prices_include_tax',false)]; return ['mode'=>$p->collection_mode,'includes'=>(bool)$p->price_includes_tax]; }
 /** Handles rates for the checkout tax calculator workflow. */
 private function rates(int $jur,?int $class,string $applies):Collection { $base=/** Inline callback for this operation. */ fn()=>TaxRate::query()->where('tax_jurisdiction_id',$jur)->where('applies_to',$applies)->where('status','active')->where(/** Inline callback for this operation. */ fn($q)=>$q->whereNull('valid_from')->orWhere('valid_from','<=',now()))->where(/** Inline callback for this operation. */ fn($q)=>$q->whereNull('valid_until')->orWhere('valid_until','>',now())); if($applies==='product'&&$class){$specific=$base()->where('tax_class_id',$class)->orderBy('id')->get();if($specific->isNotEmpty())return $specific;} return $base()->whereNull('tax_class_id')->orderBy('id')->get();}
 /** Handles compute for the checkout tax calculator workflow. */
 private function compute(int $gross,Collection $rates,bool $inclusive):array {if($gross<=0||$rates->isEmpty())return [];$sum=(int)$rates->sum('rate_bps');if($sum<=0)return $rates->map(/** Inline callback for this operation. */ fn($r)=>['rate'=>$r,'taxable'=>$gross,'tax'=>0])->all();if(!$inclusive)return $rates->map(/** Inline callback for this operation. */ fn($r)=>['rate'=>$r,'taxable'=>$gross,'tax'=>intdiv($gross*(int)$r->rate_bps,10000)])->all();$taxTotal=intdiv($gross*$sum,10000+$sum);$taxable=max(0,$gross-$taxTotal);$weights=$rates->mapWithKeys(/** Inline callback for this operation. */ fn($r)=>[(string)$r->id=>(int)$r->rate_bps]);$alloc=$this->allocate($taxTotal,$weights);return $rates->map(/** Inline callback for this operation. */ fn($r)=>['rate'=>$r,'taxable'=>$taxable,'tax'=>(int)($alloc[(string)$r->id]??0)])->all(); }
 /** Handles allocate for the checkout tax calculator workflow. */
 private function allocate(int $amount,Collection $weights):array {$keys=$weights->keys()->all();if($amount<=0||$weights->sum()<=0)return array_fill_keys($keys,0);$sum=(int)$weights->sum();$out=[];$used=0;foreach($weights as $k=>$w){$v=intdiv($amount*(int)$w,$sum);$out[(string)$k]=$v;$used+=$v;}$r=$amount-$used;foreach($keys as $k){if($r--<=0)break;$out[(string)$k]++;}return $out;}
 /** Handles save for the checkout tax calculator workflow. */
 private function save(CheckoutSession $s,int $tax,int $included,int $added,$jur):array {$meta=$s->metadata??[];$meta['tax']=['jurisdiction'=>$jur?->name,'country'=>$jur?->country_code,'region'=>$jur?->region_code,'calculatedAt'=>now()->toIso8601String()];$s->update(['tax_minor'=>$tax,'tax_included_minor'=>$included,'tax_added_minor'=>$added,'metadata'=>$meta]);return ['taxMinor'=>$tax,'taxIncludedMinor'=>$included,'taxAddedMinor'=>$added,'jurisdiction'=>$jur?->name];}
}