import {useCallback,useEffect,useState} from 'react';
import {FaPhotoVideo,FaSearch,FaTrash,FaUpload} from 'react-icons/fa';
import {Badge,Button,Card,Field,SafeImage,Select,Status} from './Toolkit';
import {apiDelete,apiGet,apiPost} from '../platform/api';

/** Provides a reusable, scoped media-library browser for admin, seller and product-picker surfaces. */
export default function MediaLibraryPanel({mode='admin',onSelect=null,compact=false}){
 const base=mode==='vendor'?'/vendor/media-library':'/admin/media-library';
 const [state,setState]=useState({items:[],vendors:[],meta:{}}),[q,setQ]=useState(''),[vendorId,setVendorId]=useState(''),[alt,setAlt]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(/** Loads the media collection for the active search and seller scope. */ async()=>{const params=new URLSearchParams();if(q.trim())params.set('q',q.trim());if(mode==='admin'&&vendorId)params.set('vendorId',vendorId);params.set('perPage',compact?'24':'60');try{setState(await apiGet(`${base}?${params}`));setError('')}catch(e){setError(e.message)}},[base,compact,mode,q,vendorId]);
 useEffect(/** Refreshes media when the current scope changes. */ ()=>{load()},[load]);
 const upload=/** Uploads one reusable image into the selected library scope. */ async file=>{if(!file)return;setBusy(true);setError('');setMessage('');try{const fd=new FormData();fd.append('file',file);if(alt.trim())fd.append('alt',alt.trim());if(mode==='admin'&&vendorId)fd.append('vendorId',vendorId);await apiPost(base,fd);setMessage('Media uploaded to the library.');setAlt('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const remove=/** Archives an unused image after confirmation. */ async item=>{if(!globalThis.confirm?.(`Archive ${item.name}?`))return;setBusy(true);setError('');try{await apiDelete(`${base}/${item.id}`);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className={`media-library ${compact?'media-library--compact':''}`}>
  {error&&<Status>{error}</Status>}{message&&<Status ok>{message}</Status>}
  <Card className="media-library-toolbar"><div className="media-library-filters"><Field label="Search media" value={q} onChange={/** Updates media search text. */ e=>setQ(e.target.value)} placeholder="Filename or alt text"/>{mode==='admin'&&<Select label="Seller scope" value={vendorId} onChange={/** Changes the admin seller media scope. */ e=>setVendorId(e.target.value)}><option value="">Global + all seller media</option>{(state.vendors||[]).map(/** Renders an admin seller option. */ v=><option key={v.id} value={v.id}>{v.name}</option>)}</Select>}<Field label="Alt text for next upload" value={alt} onChange={/** Updates upload alt text. */ e=>setAlt(e.target.value)} placeholder="Describe the image"/></div><label className="media-library-upload"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={/** Starts an image upload from the file input. */ e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value=''}}/><FaUpload/><span>{busy?'Uploading…':'Upload image'}</span></label></Card>
  <div className="media-library-grid">{(state.items||[]).map(/** Renders one reusable media-library card. */ item=><article key={item.id} className="media-library-item"><div className="media-library-thumb"><SafeImage src={item.url} alt={item.alt||item.name}/>{item.vendor?<Badge tone="primary">{item.vendor.name}</Badge>:<Badge tone="neutral">Global</Badge>}</div><div className="media-library-info"><b title={item.name}>{item.name}</b><small>{item.width&&item.height?`${item.width}×${item.height} · `:''}{item.bytes?`${Math.ceil(item.bytes/1024)} KB`:''}</small><small>{item.alt||'No alt text'}</small></div><div className="button-row">{onSelect&&<Button disabled={busy} onClick={/** Selects this library asset for the parent editor. */ ()=>onSelect(item)}>Use image</Button>}{(mode==='admin'||item.vendor)&&<Button variant="secondary" disabled={busy} onClick={/** Archives an owned media item; sellers cannot archive global media. */ ()=>remove(item)}><FaTrash/> Archive</Button>}</div></article>)}{!state.items?.length&&<Card><div className="media-library-empty"><FaPhotoVideo/><b>No media found</b><span>Upload JPG, PNG or WebP images to reuse them across products.</span></div></Card>}</div>
 </div>
}
