import {useEffect,useId,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {FaCheck,FaExclamationTriangle,FaStar,FaClock,FaArrowRight,FaSpinner,FaInbox,FaRedo,FaChevronLeft,FaChevronRight} from 'react-icons/fa';
import {countdown} from '../platform/store';
const placeholder='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="100%" height="100%" fill="#eef1f5"/><path d="M310 350l70-90 65 75 45-50 90 115H260z" fill="#cbd5e1"/><circle cx="350" cy="210" r="34" fill="#cbd5e1"/></svg>`);
/** Handles safe image for the VSN Ecommerce interface. */
export function SafeImage({src,alt='',className='',...props}){const [bad,setBad]=useState(false);useEffect(/** Inline callback for this operation. */ ()=>setBad(false),[src]);return <img className={className} src={bad||!src?placeholder:src} alt={alt} loading="lazy" decoding="async" onError={/** Inline callback for this operation. */ ()=>setBad(true)} {...props}/>}
/** Handles button for the VSN Ecommerce interface. */
export function Button({children,variant='primary',className='',loading=false,loadingLabel='Working…',icon:Icon,type,disabled,...p}){const resolvedType=type??(p.onClick?'button':'submit');return <button type={resolvedType} className={`ui-btn ui-btn--${variant} ${className}`} disabled={disabled||loading} aria-busy={loading||undefined} {...p}>{loading?<FaSpinner className="ui-spin"/>:Icon?<Icon/>:null}<span>{loading?loadingLabel:children}</span></button>}
/** Handles card for the VSN Ecommerce interface. */
export function Card({children,className='',...p}){return <section className={`ui-card ${className}`} {...p}>{children}</section>}
/** Handles field for the VSN Ecommerce interface. */
export function Field({label,error,help,required,...p}){const uid=useId();const id=p.id||`field-${uid.replaceAll(':','')}`;const helpId=help?`${id}-help`:undefined,errorId=error?`${id}-error`:undefined;return <label className={`ui-field ${error?'has-error':''}`} htmlFor={id}>{label&&<span>{label}{required&&<i aria-hidden="true">*</i>}</span>}<input id={id} required={required} aria-invalid={Boolean(error)||undefined} aria-describedby={[helpId,errorId].filter(Boolean).join(' ')||undefined} {...p}/>{help&&<small id={helpId}>{help}</small>}{error&&<em id={errorId}>{error}</em>}</label>}
/** Handles select for the VSN Ecommerce interface. */
export function Select({label,children,error,help,required,...p}){const uid=useId();const id=p.id||`select-${uid.replaceAll(':','')}`;const helpId=help?`${id}-help`:undefined,errorId=error?`${id}-error`:undefined;return <label className={`ui-field ${error?'has-error':''}`} htmlFor={id}>{label&&<span>{label}{required&&<i aria-hidden="true">*</i>}</span>}<select id={id} required={required} aria-invalid={Boolean(error)||undefined} aria-describedby={[helpId,errorId].filter(Boolean).join(' ')||undefined} {...p}>{children}</select>{help&&<small id={helpId}>{help}</small>}{error&&<em id={errorId}>{error}</em>}</label>}
/** Handles badge for the VSN Ecommerce interface. */
export function Badge({children,tone='neutral'}){return <span className={`ui-badge ui-badge--${tone}`}>{children}</span>}
/** Handles status for the VSN Ecommerce interface. */
export function Status({ok,children}){return <span className={`ui-status ${ok?'is-ok':'is-warn'}`} role={ok?'status':'alert'}>{ok?<FaCheck aria-hidden="true"/>:<FaExclamationTriangle aria-hidden="true"/>}{children}</span>}
/** Handles section header for the VSN Ecommerce interface. */
export function SectionHeader({title,sub,action,to,onAction}){const actionControl=!action?null:to?<Link className="section-head-action" to={to}>{action}<FaArrowRight aria-hidden="true"/></Link>:onAction?<button type="button" className="section-head-action" onClick={onAction}>{action}<FaArrowRight aria-hidden="true"/></button>:null;return <div className="section-head"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{actionControl}</div>}
/** Handles page header for the VSN Ecommerce interface. */
export function PageHeader({eyebrow,title,description,actions,children}){return <div className="ui-page-header"><div>{eyebrow&&<span className="ui-eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{(actions||children)&&<div className="ui-page-actions">{actions||children}</div>}</div>}
/** Handles countdown for the VSN Ecommerce interface. */
export function Countdown({target}){const [label,setLabel]=useState(/** Inline callback for this operation. */ ()=>countdown(target));useEffect(/** Inline callback for this operation. */ ()=>{const id=setInterval(/** Inline callback for this operation. */ ()=>setLabel(countdown(target)),1000);return/** Inline callback for this operation. */ ()=>clearInterval(id)},[target]);return <span className="countdown"><FaClock aria-hidden="true"/>{label}</span>}
/** Handles rating for the VSN Ecommerce interface. */
export function Rating({value,reviews}){return <span className="rating"><FaStar aria-hidden="true"/>{value} <small>({reviews?.toLocaleString()})</small></span>}
/** Handles empty state for the VSN Ecommerce interface. */
export function EmptyState({title='Nothing here yet',sub,action,actionLabel='Get started',icon:Icon=FaInbox}){return <div className="empty-state"><span className="empty-state-icon"><Icon aria-hidden="true"/></span><h3>{title}</h3>{sub&&<p>{sub}</p>}{action&&(typeof action==='string'?<Link className="ui-btn ui-btn--primary" to={action}>{actionLabel}</Link>:<Button onClick={action}>{actionLabel}</Button>)}</div>}
/** Handles error state for the VSN Ecommerce interface. */
export function ErrorState({title='Something went wrong',message='Please try again.',onRetry}){return <div className="ui-error-state" role="alert"><FaExclamationTriangle aria-hidden="true"/><div><h3>{title}</h3><p>{message}</p></div>{onRetry&&<Button variant="secondary" icon={FaRedo} onClick={onRetry}>Try again</Button>}</div>}
/** Handles skeleton for the VSN Ecommerce interface. */
export function Skeleton({lines=3,className=''}){return <div className={`ui-skeleton ${className}`} aria-hidden="true">{Array.from({length:lines}).map(/** Inline callback for this operation. */ (_,i)=><span key={i} style={{width:i===lines-1?'62%':'100%'}}/>)}</div>}
/** Handles loading state for the VSN Ecommerce interface. */
export function LoadingState({label='Loading…',cards=0}){return <div className="ui-loading-state" role="status" aria-live="polite"><span className="sr-only">{label}</span>{cards>0?<div className="ui-skeleton-grid">{Array.from({length:cards}).map(/** Inline callback for this operation. */ (_,i)=><Card key={i}><Skeleton lines={4}/></Card>)}</div>:<><FaSpinner className="ui-spin" aria-hidden="true"/><span>{label}</span></>}</div>}
/** Handles pagination for the VSN Ecommerce interface. */
export function Pagination({page=1,lastPage=1,onChange,disabled=false}){if(lastPage<=1)return null;return <nav className="ui-pagination" aria-label="Pagination"><Button variant="secondary" icon={FaChevronLeft} disabled={disabled||page<=1} onClick={/** Inline callback for this operation. */ ()=>onChange(page-1)}>Previous</Button><span>Page <b>{page}</b> of <b>{lastPage}</b></span><Button variant="secondary" disabled={disabled||page>=lastPage} onClick={/** Inline callback for this operation. */ ()=>onChange(page+1)}>Next <FaChevronRight aria-hidden="true"/></Button></nav>}
/** Returns visible, enabled focusable controls inside a dialog. */
function dialogFocusable(root){if(!root)return[];return [...root.querySelectorAll('a[href],button,input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(node=>!node.disabled&&node.getAttribute('aria-hidden')!=='true'&&node.getClientRects().length>0)}
/** Handles modal for the VSN Ecommerce interface. */
export function Modal({open,title,onClose,children,footer}){const closeRef=useRef(null),dialogRef=useRef(null),uid=useId();const titleId=`modal-title-${uid.replaceAll(':','')}`;useEffect(/** Manages dialog focus, Escape dismissal and keyboard focus containment. */ ()=>{if(!open)return undefined;const previous=document.activeElement;closeRef.current?.focus();const key=/** Keeps keyboard focus inside the active modal and supports Escape. */ e=>{if(e.key==='Escape'){e.preventDefault();onClose?.();return}if(e.key!=='Tab')return;const nodes=dialogFocusable(dialogRef.current);if(!nodes.length){e.preventDefault();closeRef.current?.focus();return}const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener('keydown',key);document.body.classList.add('modal-open');return/** Restores the page state and originating focus when the dialog closes. */ ()=>{document.removeEventListener('keydown',key);document.body.classList.remove('modal-open');previous?.focus?.()}},[open,onClose]);if(!open)return null;return <div className="modal-backdrop" role="presentation" onMouseDown={/** Closes only when the backdrop itself is activated. */ e=>e.target===e.currentTarget&&onClose?.()}><div ref={dialogRef} className="modal" role="dialog" aria-modal="true" aria-labelledby={titleId}><div className="modal-head"><h3 id={titleId}>{title}</h3><button ref={closeRef} type="button" aria-label="Close dialog" onClick={onClose}>×</button></div><div className="modal-body">{children}</div>{footer&&<div className="modal-footer">{footer}</div>}</div></div>}
