<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
return new /** Defines an anonymous class for this operation. */ class extends Migration {
    /** Applies this database migration. */
    public function up(): void {
        Schema::create('tax_jurisdictions', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->char('country_code',2)->index();$t->string('region_code',100)->nullable()->index();$t->string('name',160);$t->string('status',20)->default('active')->index();$t->unsignedInteger('priority')->default(100);$t->jsonb('metadata')->nullable();$t->timestamps();$t->unique(['country_code','region_code']);});
        Schema::create('tax_classes', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->string('code',80)->unique();$t->string('name',160);$t->text('description')->nullable();$t->boolean('is_default')->default(false)->index();$t->string('status',20)->default('active')->index();$t->timestamps();});
        Schema::create('tax_rates', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->foreignId('tax_jurisdiction_id')->constrained('tax_jurisdictions')->cascadeOnDelete();$t->foreignId('tax_class_id')->nullable()->constrained('tax_classes')->nullOnDelete();$t->string('applies_to',20)->default('product')->index();$t->string('label',120);$t->unsignedInteger('rate_bps');$t->string('status',20)->default('active')->index();$t->timestamp('valid_from')->nullable()->index();$t->timestamp('valid_until')->nullable()->index();$t->jsonb('metadata')->nullable();$t->timestamps();$t->index(['tax_jurisdiction_id','tax_class_id','applies_to','status'], 'tax_rates_lookup_idx');});
        Schema::create('vendor_tax_profiles', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->foreignId('vendor_id')->unique()->constrained()->cascadeOnDelete();$t->string('status',20)->default('pending')->index();$t->string('registered_name',190)->nullable();$t->text('tax_identifier')->nullable();$t->string('tax_identifier_last4',4)->nullable();$t->char('registration_country_code',2)->nullable();$t->string('collection_mode',20)->default('seller');$t->boolean('price_includes_tax')->default(false);$t->timestamp('verified_at')->nullable();$t->foreignId('verified_by_user_id')->nullable()->constrained('users')->nullOnDelete();$t->jsonb('metadata')->nullable();$t->timestamps();});
        Schema::table('products', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->foreignId('tax_class_id')->nullable()->constrained('tax_classes')->nullOnDelete();$t->boolean('price_includes_tax')->nullable();});
        Schema::table('checkout_sessions', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('tax_included_minor')->default(0);$t->unsignedBigInteger('tax_added_minor')->default(0);});
        Schema::table('orders', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('tax_included_minor')->default(0);$t->unsignedBigInteger('tax_added_minor')->default(0);$t->unsignedBigInteger('tax_refunded_minor')->default(0);});
        Schema::table('vendor_orders', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('tax_included_minor')->default(0);$t->unsignedBigInteger('tax_added_minor')->default(0);$t->unsignedBigInteger('platform_tax_minor')->default(0);$t->unsignedBigInteger('seller_tax_minor')->default(0);$t->unsignedBigInteger('tax_reversed_minor')->default(0);$t->unsignedBigInteger('platform_tax_reversed_minor')->default(0);$t->unsignedBigInteger('seller_tax_reversed_minor')->default(0);});
        Schema::table('order_items', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->foreignId('checkout_session_item_id')->nullable()->constrained('checkout_session_items')->nullOnDelete();$t->unsignedBigInteger('taxable_minor')->default(0);$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('tax_included_minor')->default(0);$t->unsignedBigInteger('tax_added_minor')->default(0);$t->unsignedBigInteger('platform_tax_minor')->default(0);$t->unsignedBigInteger('seller_tax_minor')->default(0);});
        Schema::table('refunds', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->unsignedBigInteger('tax_refund_minor')->default(0);});
        Schema::table('vendor_refund_adjustments', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->unsignedBigInteger('tax_reversal_minor')->default(0);$t->unsignedBigInteger('platform_tax_reversal_minor')->default(0);$t->unsignedBigInteger('seller_tax_reversal_minor')->default(0);});
        Schema::create('checkout_tax_lines', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->foreignId('checkout_session_id')->constrained()->cascadeOnDelete();$t->foreignId('checkout_session_item_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('vendor_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('tax_jurisdiction_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('tax_class_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('tax_rate_id')->nullable()->constrained()->nullOnDelete();$t->string('source',20);$t->string('source_reference',120);$t->string('label',120);$t->unsignedInteger('rate_bps');$t->unsignedBigInteger('taxable_minor');$t->unsignedBigInteger('tax_minor');$t->boolean('price_includes_tax')->default(false);$t->string('liability_bearer',20)->default('platform');$t->jsonb('metadata')->nullable();$t->timestamps();$t->index(['checkout_session_id','vendor_id']);});
        Schema::create('order_tax_lines', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('vendor_order_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('order_item_id')->nullable()->constrained()->cascadeOnDelete();$t->string('source',20);$t->string('source_reference',120);$t->string('jurisdiction_name',160)->nullable();$t->string('tax_class_code',80)->nullable();$t->string('label',120);$t->unsignedInteger('rate_bps');$t->unsignedBigInteger('taxable_minor');$t->unsignedBigInteger('tax_minor');$t->boolean('price_includes_tax')->default(false);$t->string('liability_bearer',20)->default('platform');$t->jsonb('metadata')->nullable();$t->timestamps();$t->index(['order_id','vendor_order_id']);});
        Schema::create('tax_document_sequences', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->string('scope_key',190)->unique();$t->unsignedBigInteger('next_number')->default(1);$t->timestamps();});
        Schema::create('tax_invoices', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->string('invoice_number',100)->unique();$t->foreignId('order_id')->constrained()->restrictOnDelete();$t->foreignId('vendor_order_id')->unique()->constrained()->restrictOnDelete();$t->foreignId('vendor_id')->nullable()->constrained()->nullOnDelete();$t->string('status',20)->default('issued')->index();$t->char('currency',3);$t->jsonb('seller_snapshot');$t->jsonb('buyer_snapshot');$t->unsignedBigInteger('subtotal_minor');$t->unsignedBigInteger('discount_minor')->default(0);$t->unsignedBigInteger('taxable_minor')->default(0);$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('total_minor');$t->timestamp('issued_at')->index();$t->jsonb('metadata')->nullable();$t->timestamps();});
        Schema::create('tax_invoice_items', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->foreignId('tax_invoice_id')->constrained()->cascadeOnDelete();$t->foreignId('order_item_id')->nullable()->constrained()->nullOnDelete();$t->string('kind',20)->default('product');$t->string('description',190);$t->string('sku',120)->nullable();$t->unsignedInteger('quantity')->default(1);$t->unsignedBigInteger('gross_minor');$t->unsignedBigInteger('discount_minor')->default(0);$t->unsignedBigInteger('taxable_minor')->default(0);$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('total_minor');$t->jsonb('tax_breakdown')->nullable();$t->timestamps();});
        Schema::create('tax_credit_notes', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->ulid('public_id')->unique();$t->string('credit_note_number',100)->unique();$t->foreignId('refund_id')->constrained()->restrictOnDelete();$t->foreignId('tax_invoice_id')->constrained()->restrictOnDelete();$t->foreignId('vendor_order_id')->constrained()->restrictOnDelete();$t->char('currency',3);$t->unsignedBigInteger('subtotal_minor');$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('total_minor');$t->timestamp('issued_at')->index();$t->jsonb('metadata')->nullable();$t->timestamps();$t->unique(['refund_id','tax_invoice_id']);});
        Schema::create('tax_credit_note_items', /** Inline callback for this operation. */ function(Blueprint $t):void{$t->id();$t->foreignId('tax_credit_note_id')->constrained()->cascadeOnDelete();$t->foreignId('order_item_id')->nullable()->constrained()->nullOnDelete();$t->string('description',190);$t->unsignedInteger('quantity')->default(1);$t->unsignedBigInteger('subtotal_minor');$t->unsignedBigInteger('tax_minor')->default(0);$t->unsignedBigInteger('total_minor');$t->jsonb('metadata')->nullable();$t->timestamps();});
        if(DB::getDriverName()==='pgsql'){
            DB::statement("CREATE UNIQUE INDEX tax_jurisdictions_country_region_normalized_unique ON tax_jurisdictions (country_code, COALESCE(region_code, ''))");
            DB::statement("CREATE UNIQUE INDEX tax_classes_one_default_unique ON tax_classes (is_default) WHERE is_default = true");
            foreach(['order_tax_lines','tax_invoices','tax_invoice_items','tax_credit_notes','tax_credit_note_items'] as $table){$fn='vsn_immutable_'.$table;DB::statement("CREATE OR REPLACE FUNCTION {$fn}() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION '{$table} records are immutable'; END; $$ LANGUAGE plpgsql");DB::statement("CREATE TRIGGER {$fn}_u BEFORE UPDATE OR DELETE ON {$table} FOR EACH ROW EXECUTE FUNCTION {$fn}()");}
        }
    }
    /** Reverts this database migration. */
    public function down(): void {
        if(DB::getDriverName()==='pgsql'){foreach(['order_tax_lines','tax_invoices','tax_invoice_items','tax_credit_notes','tax_credit_note_items'] as $table){$fn='vsn_immutable_'.$table;DB::statement("DROP TRIGGER IF EXISTS {$fn}_u ON {$table}");DB::statement("DROP FUNCTION IF EXISTS {$fn}()");}}
        Schema::dropIfExists('tax_credit_note_items');Schema::dropIfExists('tax_credit_notes');Schema::dropIfExists('tax_invoice_items');Schema::dropIfExists('tax_invoices');Schema::dropIfExists('tax_document_sequences');Schema::dropIfExists('order_tax_lines');Schema::dropIfExists('checkout_tax_lines');
        Schema::table('vendor_refund_adjustments',/** Inline callback for this operation. */ fn(Blueprint $t)=>$t->dropColumn(['tax_reversal_minor','platform_tax_reversal_minor','seller_tax_reversal_minor']));
        Schema::table('refunds',/** Inline callback for this operation. */ fn(Blueprint $t)=>$t->dropColumn('tax_refund_minor'));
        Schema::table('order_items',/** Inline callback for this operation. */ function(Blueprint $t):void{$t->dropConstrainedForeignId('checkout_session_item_id');$t->dropColumn(['taxable_minor','tax_minor','tax_included_minor','tax_added_minor','platform_tax_minor','seller_tax_minor']);});
        Schema::table('vendor_orders',/** Inline callback for this operation. */ fn(Blueprint $t)=>$t->dropColumn(['tax_minor','tax_included_minor','tax_added_minor','platform_tax_minor','seller_tax_minor','tax_reversed_minor','platform_tax_reversed_minor','seller_tax_reversed_minor']));
        Schema::table('orders',/** Inline callback for this operation. */ fn(Blueprint $t)=>$t->dropColumn(['tax_minor','tax_included_minor','tax_added_minor','tax_refunded_minor']));
        Schema::table('checkout_sessions',/** Inline callback for this operation. */ fn(Blueprint $t)=>$t->dropColumn(['tax_minor','tax_included_minor','tax_added_minor']));
        Schema::table('products',/** Inline callback for this operation. */ function(Blueprint $t):void{$t->dropConstrainedForeignId('tax_class_id');$t->dropColumn('price_includes_tax');});
        Schema::dropIfExists('vendor_tax_profiles');Schema::dropIfExists('tax_rates');Schema::dropIfExists('tax_classes');Schema::dropIfExists('tax_jurisdictions');
    }
};
