<?php

return [
    'demo' => [
        'enabled' => env('VSN_DEMO_SEED_ENABLED', env('APP_ENV', 'production') !== 'production'),
    ],
    'currency' => env('VSN_CURRENCY', 'PKR'),
    'coins_per_rupee' => (int) env('VSN_COINS_PER_RUPEE', 70),
    'inventory_reservation_minutes' => (int) env('VSN_INVENTORY_RESERVATION_MINUTES', 15),
    'wallet' => [
        'daily_checkin_coins' => (int) env('VSN_DAILY_CHECKIN_COINS', 70),
        'seven_day_bonus_coins' => (int) env('VSN_SEVEN_DAY_BONUS_COINS', 350),
        'max_purchase_coins' => (int) env('VSN_MAX_COIN_PURCHASE', 7000000),
        'coin_purchase_payment_minutes' => (int) env('VSN_COIN_PURCHASE_PAYMENT_MINUTES', 30),
        'promotional_expiry_days' => (int) env('VSN_PROMOTIONAL_COIN_EXPIRY_DAYS', 365),
        'expiry_batch_size' => (int) env('VSN_COIN_EXPIRY_BATCH_SIZE', 500),
    ],
    'affiliate' => [
        'rates_bps' => [1000, 900, 800, 700, 600, 500, 400, 300, 250, 200],
        'hold_days' => (int) env('VSN_AFFILIATE_HOLD_DAYS', 14),
        'terms_version' => env('VSN_AFFILIATE_TERMS_VERSION', '2026-08'),
    ],
    'reviews' => [
        'reward_percent_bps' => (int) env('VSN_REVIEW_REWARD_PERCENT_BPS', 1000),
        'coupon_expiry_days' => (int) env('VSN_REVIEW_COUPON_EXPIRY_DAYS', 90),
        'reminder_delay_days' => (int) env('VSN_REVIEW_REMINDER_DELAY_DAYS', 2),
        'image_disk' => env('VSN_REVIEW_IMAGE_DISK', 'public'),
    ],
    'returns' => [
        'window_days' => (int) env('VSN_RETURN_WINDOW_DAYS', 30),
    ],
    'finance' => [
        'payout_hold_days' => (int) env('VSN_SELLER_PAYOUT_HOLD_DAYS', 30),
        'minimum_payout_minor' => (int) env('VSN_MINIMUM_PAYOUT_MINOR', 100000),
        'require_verified_payout_method' => filter_var(env('VSN_REQUIRE_VERIFIED_PAYOUT_METHOD', true), FILTER_VALIDATE_BOOL),
        'payout_max_retries' => (int) env('VSN_PAYOUT_MAX_RETRIES', 3),
        'review_coupon_subsidy_bearer' => env('VSN_REVIEW_COUPON_SUBSIDY_BEARER', 'platform'),
    ],
    'games' => [
        'rules_version' => env('VSN_GAME_RULES_VERSION', '2026-08'),
        'max_entries_per_request' => (int) env('VSN_GAME_MAX_ENTRIES_PER_REQUEST', 20),
        'refund_batch_size' => (int) env('VSN_GAME_REFUND_BATCH_SIZE', 200),
        'max_entries_per_user' => (int) env('VSN_GAME_MAX_ENTRIES_PER_USER', 100),
    ],
    'gifts' => [
        'gift_wrap_minor' => (int) env('VSN_GIFT_WRAP_MINOR', 29_900),
        'max_schedule_days' => (int) env('VSN_GIFT_MAX_SCHEDULE_DAYS', 90),
        // Disabled by default: COD at a recipient address normally means the recipient is charged.
        'cod_enabled' => (bool) env('VSN_GIFT_COD_ENABLED', false),
        'levels' => [
            ['code'=>'starter','name'=>'Starter Gifter','min_coins'=>0,'next_reward'=>'Free gift wrap'],
            ['code'=>'silver','name'=>'Silver Gifter','min_coins'=>7_000,'unlock_reward_label'=>'Free gift wrap','unlock_rewards'=>[
                ['code'=>'free_gift_wrap','label'=>'Free gift wrap'],
            ]],
            ['code'=>'gold','name'=>'Gold Gifter','min_coins'=>35_000,'unlock_reward_label'=>'500 bonus coins','unlock_rewards'=>[
                ['code'=>'gift_bonus_500','label'=>'500 bonus coins','bonus_coins'=>500],
            ]],
            ['code'=>'platinum','name'=>'Platinum Gifter','min_coins'=>140_000,'unlock_reward_label'=>'Priority gift delivery','unlock_rewards'=>[
                ['code'=>'priority_gift_delivery','label'=>'Priority gift delivery'],
            ]],
            ['code'=>'legend','name'=>'Legend Gifter','min_coins'=>350_000,'unlock_reward_label'=>'Annual surprise box + VIP gifting concierge','unlock_rewards'=>[
                ['code'=>'annual_surprise_box','label'=>'Annual surprise box'],
                ['code'=>'vip_gifting_concierge','label'=>'VIP gifting concierge'],
            ]],
        ],
    ],
    'mobile' => [
        'access_token_minutes' => (int) env('VSN_MOBILE_ACCESS_TOKEN_MINUTES', 60),
        'refresh_token_days' => (int) env('VSN_MOBILE_REFRESH_TOKEN_DAYS', 30),
        'minimum_android_version' => env('VSN_ANDROID_MINIMUM_VERSION', '1.0.0'),
        'latest_android_version' => env('VSN_ANDROID_LATEST_VERSION', '1.0.0'),
        'android_store_url' => env('VSN_ANDROID_STORE_URL'),
        'maintenance_enabled' => (bool) env('VSN_MOBILE_MAINTENANCE_ENABLED', false),
        'maintenance_message' => env('VSN_MOBILE_MAINTENANCE_MESSAGE'),
        'maintenance_retry_after_seconds' => (int) env('VSN_MOBILE_MAINTENANCE_RETRY_AFTER_SECONDS', 300),
        'minimum_android_sdk' => (int) env('VSN_ANDROID_MINIMUM_SDK', 26),
        'oauth_app_callback_url' => env('VSN_ANDROID_OAUTH_APP_CALLBACK_URL'),
        'auth_per_minute' => (int) env('VSN_MOBILE_AUTH_PER_MINUTE', 20),
        'refresh_per_minute' => (int) env('VSN_MOBILE_REFRESH_PER_MINUTE', 30),
        'fcm' => [
            'project_id' => env('FCM_PROJECT_ID'),
            'service_account_path' => env('FCM_SERVICE_ACCOUNT_PATH'),
            'channel_id' => env('VSN_ANDROID_NOTIFICATION_CHANNEL', 'vsn_general'),
            'timeout_seconds' => (int) env('VSN_FCM_TIMEOUT_SECONDS', 10),
        ],
    ],
    'frontend_url' => env('FRONTEND_URL', 'http://localhost:8000'),
    'payments' => [
        'max_initialization_attempts' => (int) env('VSN_PAYMENT_MAX_INITIALIZATION_ATTEMPTS', 3),
        'vault' => ['max_saved_methods'=>(int) env('VSN_MAX_SAVED_PAYMENT_METHODS', 8)],
        'methods' => [
            'cod' => [
                'name' => 'Cash on delivery',
                'description' => 'Pay when the shipment is delivered.',
                'enabled' => true,
                'provider' => null,
            ],
            'card' => [
                'name' => 'Card payment',
                'description' => 'Online payment through the configured payment provider.',
                'enabled' => (bool) env('VSN_CARD_PAYMENTS_ENABLED', false),
                'provider' => env('VSN_CARD_PAYMENT_PROVIDER', 'sandbox'),
            ],
            'coins' => [
                'name' => 'VSN Coins',
                'description' => 'Pay fully with VSN Coins. Coins can also be applied to COD/card as a split payment.',
                'enabled' => true,
                'provider' => null,
            ],
        ],
        'providers' => [
            'sandbox' => [
                'webhook_secret' => env('VSN_SANDBOX_PAYMENT_WEBHOOK_SECRET', 'change-me-in-local-env'),
                'simulator_enabled' => (bool) env('VSN_SANDBOX_PAYMENT_SIMULATOR_ENABLED', false),
                'vault_secret' => env('VSN_SANDBOX_PAYMENT_VAULT_SECRET', 'change-me-in-local-env'),
                'vault_simulator_enabled' => (bool) env('VSN_SANDBOX_PAYMENT_VAULT_SIMULATOR_ENABLED', false),
            ],
            'stripe' => [
                'secret_key' => env('STRIPE_SECRET_KEY'),
                'publishable_key' => env('STRIPE_PUBLISHABLE_KEY'),
                'webhook_secret' => env('STRIPE_WEBHOOK_SECRET'),
                'api_base' => env('STRIPE_API_BASE', 'https://api.stripe.com'),
                'webhook_tolerance_seconds' => (int) env('STRIPE_WEBHOOK_TOLERANCE_SECONDS', 300),
            ],
        ],
    ],
    'shipping' => [
        'max_creation_attempts' => (int) env('VSN_SHIPPING_MAX_CREATION_ATTEMPTS', 5),
        'providers' => [
            'sandbox' => [
                'webhook_secret' => env('VSN_SANDBOX_SHIPPING_WEBHOOK_SECRET', 'change-me-in-local-env'),
                'simulator_enabled' => (bool) env('VSN_SANDBOX_SHIPPING_SIMULATOR_ENABLED', false),
            ],
            'courier_http' => [
                'base_url' => env('VSN_COURIER_API_BASE_URL'),
                'api_token' => env('VSN_COURIER_API_TOKEN'),
                'webhook_secret' => env('VSN_COURIER_WEBHOOK_SECRET'),
                'create_path' => env('VSN_COURIER_CREATE_PATH', '/shipments'),
                'lookup_path' => env('VSN_COURIER_LOOKUP_PATH', '/shipments/{id}'),
                'cancel_path' => env('VSN_COURIER_CANCEL_PATH', '/shipments/{id}/cancel'),
                'health_path' => env('VSN_COURIER_HEALTH_PATH', '/health'),
            ],
        ],
    ],
    'tax' => [
        'enabled' => (bool) env('VSN_TAX_ENABLED', false),
        'default_collection_mode' => env('VSN_TAX_DEFAULT_COLLECTION_MODE', 'none'),
        'default_prices_include_tax' => (bool) env('VSN_TAX_DEFAULT_PRICES_INCLUDE_TAX', false),
        'shipping_prices_include_tax' => (bool) env('VSN_TAX_SHIPPING_PRICES_INCLUDE_TAX', false),
        'invoice_prefix' => env('VSN_TAX_INVOICE_PREFIX', 'INV'),
        'credit_note_prefix' => env('VSN_TAX_CREDIT_NOTE_PREFIX', 'CN'),
        'invoice_expose_full_tax_id' => (bool) env('VSN_TAX_INVOICE_EXPOSE_FULL_TAX_ID', false),
    ],
    'promotions' => [
        'max_total_discount_bps' => (int) env('VSN_PROMOTION_MAX_TOTAL_DISCOUNT_BPS', 9000),
        'default_timezone' => env('VSN_PROMOTION_DEFAULT_TIMEZONE', 'Asia/Karachi'),
    ],
    'catalog' => [
        'search_per_page' => (int) env('VSN_SEARCH_PER_PAGE', 24),
        'alert_scan_limit' => (int) env('VSN_PRODUCT_ALERT_SCAN_LIMIT', 1000),
        'media_disk' => env('VSN_PRODUCT_MEDIA_DISK', 'public'),
        'max_product_images' => (int) env('VSN_MAX_PRODUCT_IMAGES', 10),
        'product_view_dedup_minutes' => (int) env('VSN_PRODUCT_VIEW_DEDUP_MINUTES', 30),
        'product_view_retention_days' => (int) env('VSN_PRODUCT_VIEW_RETENTION_DAYS', 180),
        'search_history_retention_days' => (int) env('VSN_SEARCH_HISTORY_RETENTION_DAYS', 90),
        'trending_search_min_count' => (int) env('VSN_TRENDING_SEARCH_MIN_COUNT', 3),
    ],
    'notifications' => [
        'email_provider' => env('VSN_TRANSACTIONAL_EMAIL_PROVIDER', 'laravel_mail'),
        'providers' => [
            'resend' => [
                'api_key' => env('RESEND_API_KEY'),
                'from' => env('RESEND_FROM_ADDRESS', env('MAIL_FROM_ADDRESS')),
                'api_base' => env('RESEND_API_BASE', 'https://api.resend.com'),
            ],
        ],
        'backfill_days' => (int) env('VSN_NOTIFICATION_BACKFILL_DAYS', 30),
        'delivery_batch_size' => (int) env('VSN_NOTIFICATION_DELIVERY_BATCH_SIZE', 200),
        'max_attempts' => (int) env('VSN_NOTIFICATION_MAX_ATTEMPTS', 3),
    ],
    'kyc' => [
        'document_disk' => env('VSN_KYC_DOCUMENT_DISK', 'local'),
        'provider' => env('VSN_KYC_PROVIDER', 'manual'),
        'government_id_valid_days' => (int) env('VSN_KYC_GOVERNMENT_ID_VALID_DAYS', 365),
        'address_proof_valid_days' => (int) env('VSN_KYC_ADDRESS_PROOF_VALID_DAYS', 180),
        'retry_batch_size' => (int) env('VSN_KYC_RETRY_BATCH_SIZE', 100),
        'max_provider_attempts' => (int) env('VSN_KYC_MAX_PROVIDER_ATTEMPTS', 5),
        'providers' => [
            'kyc_http' => [
                'base_url' => env('VSN_KYC_API_BASE_URL'),
                'api_token' => env('VSN_KYC_API_TOKEN'),
                'webhook_secret' => env('VSN_KYC_WEBHOOK_SECRET'),
                'submit_path' => env('VSN_KYC_SUBMIT_PATH', '/verifications'),
                'lookup_path' => env('VSN_KYC_LOOKUP_PATH', '/verifications/{id}'),
                'health_path' => env('VSN_KYC_HEALTH_PATH', '/health'),
            ],
        ],
    ],
    'security' => [
        'sms_provider' => env('VSN_SMS_PROVIDER', 'sandbox'),
        'providers' => [
            'twilio' => [
                'account_sid' => env('TWILIO_ACCOUNT_SID'),
                'auth_token' => env('TWILIO_AUTH_TOKEN'),
                'from' => env('TWILIO_FROM'),
                'messaging_service_sid' => env('TWILIO_MESSAGING_SERVICE_SID'),
                'api_base' => env('TWILIO_API_BASE', 'https://api.twilio.com'),
            ],
        ],
        'sandbox_sms_enabled' => (bool) env('VSN_SANDBOX_SMS_ENABLED', false),
        'step_up_minutes' => (int) env('VSN_SECURITY_STEP_UP_MINUTES', 10),
        'seller_payout_requires_phone' => (bool) env('VSN_PAYOUT_REQUIRE_PHONE_VERIFICATION', true),
        'seller_payout_requires_identity' => (bool) env('VSN_PAYOUT_REQUIRE_IDENTITY_KYC', true),
        'max_api_request_bytes' => (int) env('VSN_MAX_API_REQUEST_BYTES', 2_097_152),
        'max_upload_request_bytes' => (int) env('VSN_MAX_UPLOAD_REQUEST_BYTES', 52_428_800),
        'csp' => [
            'enabled' => filter_var(env('VSN_CSP_ENABLED', true), FILTER_VALIDATE_BOOL),
        ],
        'uploads' => [
            'max_file_bytes' => (int) env('VSN_UPLOAD_MAX_FILE_BYTES', 10_485_760),
            'max_image_dimension' => (int) env('VSN_UPLOAD_MAX_IMAGE_DIMENSION', 12_000),
            'max_image_pixels' => (int) env('VSN_UPLOAD_MAX_IMAGE_PIXELS', 50_000_000),
        ],
    ],

    'reporting' => [
        'timezone' => env('VSN_REPORTING_TIMEZONE', 'Asia/Karachi'),
        'export_disk' => env('VSN_REPORT_EXPORT_DISK', 'local'),
        'export_retention_days' => (int) env('VSN_REPORT_EXPORT_RETENTION_DAYS', 14),
        'max_dashboard_days' => (int) env('VSN_REPORT_MAX_DASHBOARD_DAYS', 366),
        'max_export_rows' => (int) env('VSN_REPORT_MAX_EXPORT_ROWS', 100000),
        'max_cohort_customers' => (int) env('VSN_REPORT_MAX_COHORT_CUSTOMERS', 50000),
        'generate_batch_size' => (int) env('VSN_REPORT_GENERATE_BATCH_SIZE', 10),
        'schedule_batch_size' => (int) env('VSN_REPORT_SCHEDULE_BATCH_SIZE', 100),
    ],

    'risk' => [
        // Automated scoring is evidence for review. Explicit holds and velocity limits are the default hard controls.
        'mode' => env('VSN_RISK_MODE', 'observe'),
        'review_score' => (int) env('VSN_RISK_REVIEW_SCORE', 50),
        'critical_score' => (int) env('VSN_RISK_CRITICAL_SCORE', 75),
        'auto_hold_critical' => (bool) env('VSN_RISK_AUTO_HOLD_CRITICAL', false),
        'velocity' => [
            'payment_intents_per_15m' => (int) env('VSN_RISK_PAYMENT_INTENTS_PER_15M', 8),
            'wallet_transfers_per_hour' => (int) env('VSN_RISK_WALLET_TRANSFERS_PER_HOUR', 10),
            'wallet_transfer_coins_per_day' => (int) env('VSN_RISK_WALLET_TRANSFER_COINS_PER_DAY', 350000),
            'game_entries_per_hour' => (int) env('VSN_RISK_GAME_ENTRIES_PER_HOUR', 100),
            'return_requests_per_day' => (int) env('VSN_RISK_RETURN_REQUESTS_PER_DAY', 5),
        ],
        'signals' => [
            'wallet_transfer_coins_24h' => (int) env('VSN_RISK_SIGNAL_WALLET_COINS_24H', 175000),
            'game_entries_24h' => (int) env('VSN_RISK_SIGNAL_GAME_ENTRIES_24H', 150),
        ],
    ],
    'messaging' => [
        'attachment_disk' => env('VSN_MESSAGE_ATTACHMENT_DISK', 'local'),
        'poll_seconds' => (int) env('VSN_MESSAGE_POLL_SECONDS', 12),
    ],
    'providers' => [
        'health_max_age_minutes' => (int) env('VSN_PROVIDER_HEALTH_MAX_AGE_MINUTES', 15),
        'reconciliation_limit' => (int) env('VSN_PROVIDER_RECONCILIATION_LIMIT', 200),
        'reconciliation_max_age_hours' => (int) env('VSN_PROVIDER_RECONCILIATION_MAX_AGE_HOURS', 24),
    ],
    'shipping_methods' => [
        'standard' => [
            'name' => 'Standard delivery',
            'eta' => '3–5 business days',
            'per_vendor_minor' => 25_000,
            'provider' => env('VSN_STANDARD_SHIPPING_PROVIDER', 'sandbox'),
            'dispatch_sla_hours' => (int) env('VSN_STANDARD_DISPATCH_SLA_HOURS', 24),
            'delivery_sla_hours' => (int) env('VSN_STANDARD_DELIVERY_SLA_HOURS', 120),
            'enabled' => true,
        ],
        'express' => [
            'name' => 'Express delivery',
            'eta' => '1–2 business days',
            'per_vendor_minor' => 65_000,
            'provider' => env('VSN_EXPRESS_SHIPPING_PROVIDER', 'sandbox'),
            'dispatch_sla_hours' => (int) env('VSN_EXPRESS_DISPATCH_SLA_HOURS', 12),
            'delivery_sla_hours' => (int) env('VSN_EXPRESS_DELIVERY_SLA_HOURS', 48),
            'enabled' => true,
        ],
    ],
    'operations' => [
        'release' => env('VSN_RELEASE', '0.34.0'),
        'health_disk' => env('VSN_HEALTH_DISK', 'local'),
        'require_scheduler' => (bool) env('VSN_HEALTH_REQUIRE_SCHEDULER', false),
        'require_queue_worker' => (bool) env('VSN_HEALTH_REQUIRE_QUEUE_WORKER', false),
        'require_queue_pressure' => (bool) env('VSN_HEALTH_REQUIRE_QUEUE_PRESSURE', false),
        'scheduler_stale_seconds' => (int) env('VSN_SCHEDULER_STALE_SECONDS', 180),
        'queue_worker_stale_seconds' => (int) env('VSN_QUEUE_WORKER_STALE_SECONDS', 180),
        'slow_query_ms' => (int) env('VSN_SLOW_QUERY_MS', 500),
        'monitored_queues' => array_values(array_filter(explode(',', (string) env('VSN_MONITORED_QUEUES', 'critical,maintenance,default,notifications,reports')))),
        'queue_busy_max' => (int) env('VSN_QUEUE_BUSY_MAX', 500),
        'deployment' => [
            'require_verified_backup' => filter_var(env('VSN_DEPLOY_REQUIRE_VERIFIED_BACKUP', true), FILTER_VALIDATE_BOOL),
            'require_artifact_sha' => filter_var(env('VSN_DEPLOY_REQUIRE_ARTIFACT_SHA', true), FILTER_VALIDATE_BOOL),
            'require_dependency_locks' => filter_var(env('VSN_DEPLOY_REQUIRE_DEPENDENCY_LOCKS', env('APP_ENV', 'production') === 'production'), FILTER_VALIDATE_BOOL),
            'max_active_incident_severity' => env('VSN_DEPLOY_MAX_ACTIVE_INCIDENT_SEVERITY', 'sev3'),
        ],
        'async_scheduler' => (bool) env('VSN_ASYNC_SCHEDULER', false),
        'rate_limits' => [
            'guest_per_minute' => (int) env('VSN_RATE_GUEST_PER_MINUTE', 180),
            'authenticated_per_minute' => (int) env('VSN_RATE_AUTHENTICATED_PER_MINUTE', 600),
            'auth_per_minute' => (int) env('VSN_RATE_AUTH_PER_MINUTE', 30),
            'catalog_read_per_minute' => (int) env('VSN_RATE_CATALOG_READ_PER_MINUTE', 240),
            'commerce_write_per_minute' => (int) env('VSN_RATE_COMMERCE_WRITE_PER_MINUTE', 90),
            'upload_per_minute' => (int) env('VSN_RATE_UPLOAD_PER_MINUTE', 20),
            'webhook_per_minute' => (int) env('VSN_RATE_WEBHOOK_PER_MINUTE', 300),
            'sensitive_per_minute' => (int) env('VSN_RATE_SENSITIVE_PER_MINUTE', 12),
        ],
        'backups' => [
            'enabled' => (bool) env('VSN_BACKUPS_ENABLED', false),
            'disk' => env('VSN_BACKUP_DISK', 'local'),
            'retention_days' => (int) env('VSN_BACKUP_RETENTION_DAYS', 14),
            'timeout_seconds' => (int) env('VSN_BACKUP_TIMEOUT_SECONDS', 600),
            'mysql_dump_binary' => env('VSN_MYSQL_DUMP_BINARY', 'mysqldump'),
            'mysql_no_tablespaces' => (bool) env('VSN_MYSQL_DUMP_NO_TABLESPACES', true),
            'pg_dump_binary' => env('VSN_PG_DUMP_BINARY', 'pg_dump'),
        ],
        'launch' => [
            'max_failed_jobs' => (int) env('VSN_LAUNCH_MAX_FAILED_JOBS', 0),
            'max_verified_backup_age_hours' => (int) env('VSN_LAUNCH_BACKUP_MAX_AGE_HOURS', 30),
            'require_verification_manifest' => (bool) env('VSN_LAUNCH_REQUIRE_VERIFICATION_MANIFEST', false),
            'verification_manifest' => env('VSN_LAUNCH_VERIFICATION_MANIFEST', base_path('runtime/launch-verification.json')),
        ],
    ],
    'performance' => [
        'query_telemetry' => filter_var(env('VSN_QUERY_TELEMETRY_ENABLED', true), FILTER_VALIDATE_BOOL),
        'request_budget_ms' => (int) env('VSN_REQUEST_BUDGET_MS', 1500),
        'query_budget' => (int) env('VSN_QUERY_BUDGET', 80),
        'duplicate_query_budget' => (int) env('VSN_DUPLICATE_QUERY_BUDGET', 8),
        'memory_budget_mb' => (int) env('VSN_MEMORY_BUDGET_MB', 96),
        'expose_server_timing' => filter_var(env('VSN_EXPOSE_SERVER_TIMING', env('APP_ENV', 'production') !== 'production'), FILTER_VALIDATE_BOOL),
        'catalog_cache_seconds' => (int) env('VSN_CATALOG_CACHE_SECONDS', 120),
        'suggestion_cache_seconds' => (int) env('VSN_SEARCH_SUGGESTION_CACHE_SECONDS', 30),
        'trending_cache_seconds' => (int) env('VSN_TRENDING_CACHE_SECONDS', 60),
    ],
    'go_live' => [
        'rollback_window_minutes' => (int) env('VSN_GO_LIVE_ROLLBACK_WINDOW_MINUTES', 120),
        'stabilization_minutes' => (int) env('VSN_GO_LIVE_STABILIZATION_MINUTES', 240),
        'observation_interval_minutes' => (int) env('VSN_GO_LIVE_OBSERVATION_INTERVAL_MINUTES', 5),
        'required_healthy_observations' => (int) env('VSN_GO_LIVE_REQUIRED_HEALTHY_OBSERVATIONS', 6),
        'max_failed_jobs' => (int) env('VSN_GO_LIVE_MAX_FAILED_JOBS', 0),
        'max_notification_failed' => (int) env('VSN_GO_LIVE_MAX_NOTIFICATION_FAILED', 0),
        'max_notification_backlog' => (int) env('VSN_GO_LIVE_MAX_NOTIFICATION_BACKLOG', 500),
        'max_payment_failure_percent' => (float) env('VSN_GO_LIVE_MAX_PAYMENT_FAILURE_PERCENT', 10),
        'payment_failure_minimum_attempts' => (int) env('VSN_GO_LIVE_PAYMENT_FAILURE_MIN_ATTEMPTS', 10),
        'max_sev3_incidents' => (int) env('VSN_GO_LIVE_MAX_SEV3_INCIDENTS', 2),
        'provider_health_max_age_minutes' => (int) env('VSN_GO_LIVE_PROVIDER_HEALTH_MAX_AGE_MINUTES', 15),
        'finance_reconciliation_max_age_minutes' => (int) env('VSN_GO_LIVE_FINANCE_RECONCILIATION_MAX_AGE_MINUTES', 75),
        'auto_open_incident' => filter_var(env('VSN_GO_LIVE_AUTO_OPEN_INCIDENT', true), FILTER_VALIDATE_BOOL),
        'require_distinct_signers' => filter_var(env('VSN_GO_LIVE_REQUIRE_DISTINCT_SIGNERS', env('APP_ENV', 'production') === 'production'), FILTER_VALIDATE_BOOL),
        'required_signoffs' => array_values(array_filter(array_map('trim', explode(',', (string) env('VSN_GO_LIVE_REQUIRED_SIGNOFFS', 'operations,finance,business_owner'))))),
    ],
    'acceptance' => [
        'acceptance_valid_minutes' => (int) env('VSN_ACCEPTANCE_VALID_MINUTES', 120),
        'drill_max_age_days' => (int) env('VSN_ACCEPTANCE_DRILL_MAX_AGE_DAYS', 90),
        'rto_target_minutes' => (int) env('VSN_ACCEPTANCE_RTO_TARGET_MINUTES', 60),
        'rpo_target_minutes' => (int) env('VSN_ACCEPTANCE_RPO_TARGET_MINUTES', 1440),
        'max_product_view_retention_days' => (int) env('VSN_ACCEPTANCE_MAX_PRODUCT_VIEW_RETENTION_DAYS', 365),
        'max_report_retention_days' => (int) env('VSN_ACCEPTANCE_MAX_REPORT_RETENTION_DAYS', 30),
        'require_distinct_signers' => filter_var(env('VSN_ACCEPTANCE_REQUIRE_DISTINCT_SIGNERS', env('APP_ENV', 'production') === 'production'), FILTER_VALIDATE_BOOL),
        'runtime_evidence_max_age_minutes' => (int) env('VSN_ACCEPTANCE_RUNTIME_EVIDENCE_MAX_AGE_MINUTES', 180),
        'verification_manifest' => env('VSN_ACCEPTANCE_VERIFICATION_MANIFEST', base_path('runtime/final-acceptance-verification.json')),
        'release_candidate_manifest_path' => env('VSN_RELEASE_CANDIDATE_MANIFEST', base_path('runtime/final-release-candidate.json')),
        'required_runtime_flags' => [
            'composerLock','npmLock','dependencies','databaseMigrations','laravelTests','frontendBuild',
            'appSmoke','authenticatedE2E','queueHeartbeat','schedulerHeartbeat','backupRestoreDrill','providerContracts',
            'mysqlMigrationAudit','databasePortabilityAudit','performanceSecurityAudit','productionOperationsAudit',
            'authAdminAudit','runtimeCapabilityAudit','dependencyLocksBound','browserE2E','androidApiSmoke',
        ],
        'required_runbooks' => [
            'docs/runbooks/GO-LIVE-OPERATOR-HANDBOOK.md',
            'docs/runbooks/SEV1-INCIDENT.md',
            'docs/runbooks/SECURITY-INCIDENT.md',
            'docs/runbooks/DATABASE-RECOVERY.md',
            'docs/runbooks/PROVIDER-OUTAGE.md',
            'docs/SECURITY-PRIVACY-ACCEPTANCE.md',
        ],
    ],

];
