<?php
namespace App\Domain\Risk\Services;
use App\Enums\{PaymentTransactionStatus,PaymentTransactionType,WalletEntryDirection,WalletTransactionType};
use App\Models\{AffiliateRelationship,GameEntry,Order,PaymentTransaction,Refund,ReturnRequest,RiskCase,RiskHold,RiskProfile,SavedPaymentMethod,SecurityEvent,Shipment,User,UserDevice,Vendor,VendorOrder,VendorSettlement,WalletEntry};
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
/** Defines the RiskEvaluator class and its project responsibilities. */
class RiskEvaluator {
    /** Initializes the RiskEvaluator instance and its dependencies. */
    public function __construct(private readonly RiskRecorder $events){}
    /** Handles user for the risk evaluator workflow. */
    public function user(User $user,string $trigger='scheduled'):RiskProfile {
        $signals=[];$score=0;
        $failed=SecurityEvent::query()->where('user_id',$user->id)->whereIn('type',['login_failed','login_rate_limited'])->where('created_at','>=',now()->subDay())->count();if($failed>=5){$points=min(20,5+($failed-5)*2);$signals['failedLogins24h']=['value'=>$failed,'points'=>$points];$score+=$points;}
        $newDevices=UserDevice::query()->where('user_id',$user->id)->where('first_seen_at','>=',now()->subDays(7))->count();if($newDevices>=4){$points=min(15,$newDevices*2);$signals['newDevices7d']=['value'=>$newDevices,'points'=>$points];$score+=$points;}
        $hashes=UserDevice::query()->where('user_id',$user->id)->pluck('device_key_hash');$shared=$hashes->isEmpty()?0:UserDevice::query()->whereIn('device_key_hash',$hashes)->where('user_id','<>',$user->id)->distinct()->count('user_id');if($shared>0){$points=min(35,20+$shared*5);$signals['sharedDeviceAccounts']=['value'=>$shared,'points'=>$points];$score+=$points;}
        $fingerprints=SavedPaymentMethod::query()->where('user_id',$user->id)->whereNotNull('fingerprint_sha256')->pluck('fingerprint_sha256');$sharedPayment=$fingerprints->isEmpty()?0:SavedPaymentMethod::query()->whereIn('fingerprint_sha256',$fingerprints)->where('user_id','<>',$user->id)->distinct()->count('user_id');if($sharedPayment>0){$points=min(35,25+$sharedPayment*5);$signals['sharedPaymentInstrumentAccounts']=['value'=>$sharedPayment,'points'=>$points];$score+=$points;}
        $phone=$user->profile?->phone_verified_at?$user->profile?->phone:null;$sharedPhone=$phone?\App\Models\UserProfile::query()->where('phone',$phone)->whereNotNull('phone_verified_at')->where('user_id','<>',$user->id)->count():0;if($sharedPhone>0){$points=min(20,10+$sharedPhone*5);$signals['sharedVerifiedPhoneAccounts']=['value'=>$sharedPhone,'points'=>$points];$score+=$points;}
        $paymentFailures=PaymentTransaction::query()->whereHas('paymentIntent',/** Inline callback for this operation. */ fn($q)=>$q->where('user_id',$user->id))->where(/** Inline callback for this operation. */ function($q){$q->where('type',PaymentTransactionType::Failure->value)->orWhere('status',PaymentTransactionStatus::Failed->value);})->where('occurred_at','>=',now()->subDay())->count();if($paymentFailures>=3){$points=min(20,5+$paymentFailures*3);$signals['paymentFailures24h']=['value'=>$paymentFailures,'points'=>$points];$score+=$points;}
        $transferCoins=(int)WalletEntry::query()->where('user_id',$user->id)->where('direction',WalletEntryDirection::Debit->value)->whereHas('transaction',/** Inline callback for this operation. */ fn($q)=>$q->whereIn('type',[WalletTransactionType::Transfer->value,WalletTransactionType::Gift->value])->where('occurred_at','>=',now()->subDay()))->sum('coins');$transferThreshold=(int)config('vsn.risk.signals.wallet_transfer_coins_24h',175000);if($transferCoins>$transferThreshold){$points=min(20,10+(int)floor($transferCoins/max(1,$transferThreshold))*3);$signals['walletTransferCoins24h']=['value'=>$transferCoins,'points'=>$points];$score+=$points;}
        $gameEntries=(int)GameEntry::query()->where('user_id',$user->id)->where('created_at','>=',now()->subDay())->sum('quantity');if($gameEntries>=(int)config('vsn.risk.signals.game_entries_24h',150)){$points=15;$signals['gameEntries24h']=['value'=>$gameEntries,'points'=>$points];$score+=$points;}
        $orders=Order::query()->where('user_id',$user->id)->where('placed_at','>=',now()->subDays(90))->count();$returns=ReturnRequest::query()->where('user_id',$user->id)->where('submitted_at','>=',now()->subDays(90))->count();if($returns>=3&&$orders>0){$ratio=$returns/$orders;if($ratio>=0.5){$points=min(25,10+(int)round($ratio*15));$signals['returnOrderRatio90d']=['value'=>round($ratio,3),'returns'=>$returns,'orders'=>$orders,'points'=>$points];$score+=$points;}}
        $parentId=(int)(AffiliateRelationship::query()->where('user_id',$user->id)->value('parent_user_id')??0);if($parentId&&$hashes->isNotEmpty()){$sharedWithParent=UserDevice::query()->where('user_id',$parentId)->whereIn('device_key_hash',$hashes)->exists();if($sharedWithParent){$points=30;$signals['affiliateSharedDeviceWithReferrer']=['value'=>true,'points'=>$points];$score+=$points;}}
        $score=min(100,$score);$level=$score>=75?'critical':($score>=50?'high':($score>=25?'medium':'low'));
        $profile=RiskProfile::query()->updateOrCreate(['user_id'=>$user->id],['public_id'=>RiskProfile::query()->where('user_id',$user->id)->value('public_id')?:((string)Str::ulid()),'score'=>$score,'level'=>$level,'status'=>'monitored','signal_summary'=>$signals?:null,'last_evaluated_at'=>now()]);
        $this->maybeCase($profile,$user,null,$trigger);
        return $profile;
    }
    /** Handles vendor for the risk evaluator workflow. */
    public function vendor(Vendor $vendor,string $trigger='scheduled'):RiskProfile {
        $signals=[];$score=0;$orders=VendorOrder::query()->where('vendor_id',$vendor->id)->where('created_at','>=',now()->subDays(90))->count();
        $shipments=Shipment::query()->where('vendor_id',$vendor->id)->where('created_at','>=',now()->subDays(90));$shipmentCount=(clone $shipments)->count();$failed=(clone $shipments)->whereNotNull('failed_at')->count();$rto=(clone $shipments)->whereNotNull('rto_at')->count();if($shipmentCount>=5){$failureRatio=($failed+$rto)/$shipmentCount;if($failureRatio>=0.2){$points=min(30,10+(int)round($failureRatio*50));$signals['failedDeliveryRatio90d']=['value'=>round($failureRatio,3),'points'=>$points];$score+=$points;}}
        $gross=(int)VendorOrder::query()->where('vendor_id',$vendor->id)->where('created_at','>=',now()->subDays(90))->sum('subtotal_minor');$refunded=(int)VendorOrder::query()->where('vendor_id',$vendor->id)->where('created_at','>=',now()->subDays(90))->sum('refunded_minor');if($gross>0&&$refunded>0){$ratio=$refunded/$gross;if($ratio>=0.2){$points=min(30,10+(int)round($ratio*50));$signals['refundValueRatio90d']=['value'=>round($ratio,3),'points'=>$points];$score+=$points;}}
        $recovery=(int)VendorSettlement::query()->where('vendor_id',$vendor->id)->sum('seller_recovery_offset_minor');if($recovery>0){$points=15;$signals['sellerRecoveryOffset']=['value'=>$recovery,'points'=>$points];$score+=$points;}
        $dispatchBreaches=Shipment::query()->where('vendor_id',$vendor->id)->whereNotNull('dispatch_breached_at')->where('created_at','>=',now()->subDays(90))->count();if($orders>=5&&$dispatchBreaches/max(1,$orders)>=0.3){$points=15;$signals['dispatchSlaBreaches90d']=['value'=>$dispatchBreaches,'points'=>$points];$score+=$points;}
        $score=min(100,$score);$level=$score>=75?'critical':($score>=50?'high':($score>=25?'medium':'low'));
        $profile=RiskProfile::query()->updateOrCreate(['vendor_id'=>$vendor->id],['public_id'=>RiskProfile::query()->where('vendor_id',$vendor->id)->value('public_id')?:((string)Str::ulid()),'score'=>$score,'level'=>$level,'status'=>'monitored','signal_summary'=>$signals?:null,'last_evaluated_at'=>now()]);$this->maybeCase($profile,null,$vendor,$trigger);return $profile;
    }
    /** Handles maybe case for the risk evaluator workflow. */
    private function maybeCase(RiskProfile $profile,?User $user,?Vendor $vendor,string $trigger):void {
        $threshold=(int)config('vsn.risk.review_score',50);if($profile->score<$threshold)return;
        $open=RiskCase::query()->where('status','<>','resolved')->where('status','<>','dismissed')->when($user,/** Inline callback for this operation. */ fn($q)=>$q->where('user_id',$user->id))->when($vendor,/** Inline callback for this operation. */ fn($q)=>$q->where('vendor_id',$vendor->id))->exists();if($open)return;
        $case=RiskCase::create(['public_id'=>(string)Str::ulid(),'user_id'=>$user?->id,'vendor_id'=>$vendor?->id,'status'=>'open','priority'=>$profile->level==='critical'?'critical':'high','title'=>($vendor?'Seller':'Account').' risk review','summary'=>'Automated signals crossed the manual review threshold.','score_at_open'=>$profile->score,'metadata'=>['trigger'=>$trigger,'signals'=>$profile->signal_summary],'opened_at'=>now()]);
        $this->events->record($user,$vendor,'risk_case_opened',$profile->level==='critical'?'critical':'high',0,'all','risk_case',$case->public_id,"risk-case:{$case->public_id}",['score'=>$profile->score]);
        if($profile->score>=(int)config('vsn.risk.critical_score',75)&&config('vsn.risk.auto_hold_critical',false)){$scopes=$vendor?['payouts']:['payments','wallet','games','returns','affiliate'];foreach($scopes as $scope)RiskHold::create(['public_id'=>(string)Str::ulid(),'user_id'=>$user?->id,'vendor_id'=>$vendor?->id,'risk_case_id'=>$case->id,'scope'=>$scope,'status'=>'active','reason'=>'Automatic critical-risk hold pending manual review.','starts_at'=>now()]);}
    }
}
