<?php

declare(strict_types=1);
$root=dirname(__DIR__);$checks=[];$errors=[];
$read=static /** Inline callback for this operation. */ fn(string $p):string=>is_file($root.'/'.$p)?(string)file_get_contents($root.'/'.$p):'';
$has=static /** Inline callback for this operation. */ function(string $label,bool $ok,string $detail='')use(&$checks,&$errors):void{$checks[]=['label'=>$label,'ok'=>$ok,'detail'=>$detail];if(!$ok)$errors[]=$label.($detail?': '.$detail:'');};
$migration=$read('database/migrations/2026_08_12_210000_finalize_release_candidate_acceptance.php');
$service=$read('app/Domain/Operations/Services/ProductionAcceptanceService.php');
$controller=$read('app/Http/Controllers/Api/V1/AdminAcceptanceController.php');
$routes=$read('routes/api.php');$console=$read('routes/console.php');$config=$read('config/vsn.php');$prod=$read('.env.production.example');
$has('release candidate table',str_contains($migration,"Schema::create('release_candidate_manifests'"));
foreach(['deployment_run_id','artifact_sha256','verification_sha256','evidence_sha256'] as $column)$has('acceptance evidence column '.$column,str_contains($migration,"'{$column}'"));
$has('RC MySQL update immutability',str_contains($migration,'rc_manifest_immutable_upd'));
$has('RC MySQL delete immutability',str_contains($migration,'rc_manifest_immutable_del'));
$has('signoff MySQL immutability',str_contains($migration,'acceptance_signoff_immutable_upd'));
$has('DR MySQL immutability',str_contains($migration,'dr_evidence_immutable_upd'));
$has('RC PostgreSQL immutability',str_contains($migration,'vsn_block_rc_manifest_mutation'));
foreach(['deployment_evidence','final_runtime_evidence','release_identity'] as $code)$has('acceptance check '.$code,str_contains($service,"'{$code}'"));
$has('artifact bound to runtime evidence',str_contains($service,'artifactMatch'));
$has('verification SHA captured',str_contains($service,"'verificationSha256'"));
$has('acceptance evidence SHA captured',str_contains($service,"'evidenceSha256'"));
$has('distinct signer enforcement',str_contains($service,'require_distinct_signers'));
$has('changed evidence blocks signoff',str_contains($service,'Release candidate evidence changed after this acceptance snapshot'));
$has('seal requires approved run',str_contains($service,"\$run->status==='approved'"));
$has('seal binds artifact SHA',str_contains($service,"'artifactSha256'=>\$run->artifact_sha256"));
$has('seal binds verification SHA',str_contains($service,"'verificationSha256'=>\$run->verification_sha256"));
$has('seal binds acceptance SHA',str_contains($service,"'acceptanceEvidenceSha256'=>\$run->evidence_sha256"));
$has('go-live requires RC seal',str_contains($service,'releaseCandidateSealed'));
$has('RC manifest file output',str_contains($service,'final-release-candidate.json'));
$has('Super Admin seal controller',str_contains($controller,'function seal')&&str_contains($controller,'UserRole::SuperAdmin'));
$has('seal API route',str_contains($routes,"/admin/system/acceptance/{acceptanceRun}/seal"));
$has('RC seal CLI command',str_contains($console,"vsn:rc-seal"));
$has('go-live CLI remains final gate',str_contains($console,"vsn:go-live-gate"));
$has('final static evidence script',is_file($root.'/scripts/final-static-acceptance.sh'));
$has('final evidence aggregator',is_file($root.'/scripts/final-acceptance-evidence.php'));
$aggregate=$read('scripts/final-acceptance-evidence.php');
foreach(['launch','release-metadata','static','browser','android'] as $source)$has('aggregator source '.$source,str_contains($aggregate,"'{$source}'"));
$has('aggregator checks commit identity',str_contains($aggregate,'evidence commit does not match deployed commit'));
$has('aggregator checks release identity',str_contains($aggregate,'Launch verification release does not match release metadata'));
$has('aggregator writes artifact identity',str_contains($aggregate,"'artifactSha256'"));
$release=$read('scripts/release-production.sh');
$has('deployment writes release metadata',str_contains($release,'release-metadata.json'));
$has('release metadata artifact SHA',str_contains($release,'artifactSha256'));
$runtime=$read('scripts/runtime-verify.sh');
$has('runtime verification uses configured release',str_contains($runtime,'VSN_RELEASE:-runtime-verification'));
$android=$read('scripts/android-api-smoke.sh');
$has('Android smoke writes evidence',str_contains($android,'android-api-smoke.json'));
$ci=$read('.github/workflows/ci.yml');
$has('browser CI writes evidence',str_contains($ci,'browser-e2e.json'));
$has('production requires distinct signers',str_contains($prod,'VSN_ACCEPTANCE_REQUIRE_DISTINCT_SIGNERS=true'));
$has('production final evidence path shared',str_contains($prod,'/var/www/vsn/shared/runtime/final-acceptance-verification.json'));
$has('production RC manifest path shared',str_contains($prod,'/var/www/vsn/shared/runtime/final-release-candidate.json'));
$required=['browserE2E','androidApiSmoke','performanceSecurityAudit','productionOperationsAudit','mysqlMigrationAudit','databasePortabilityAudit','authAdminAudit'];
foreach($required as $flag)$has('required final evidence flag '.$flag,str_contains($config,"'{$flag}'"));
$has('AX tests present',is_file($root.'/tests/Feature/FinalProductionAcceptanceTest.php'));
$has('AX operator runbook present',is_file($root.'/docs/FINAL-PRODUCTION-ACCEPTANCE.md'));
foreach($checks as $c)echo($c['ok']?'[PASS] ':'[FAIL] ').$c['label'].($c['detail']?' ('.$c['detail'].')':'').PHP_EOL;
echo PHP_EOL.'Checks: '.count($checks).' | Failures: '.count($errors).PHP_EOL;if($errors){foreach($errors as $e)fwrite(STDERR,' - '.$e.PHP_EOL);exit(1);} 
