<?php
$root=dirname(__DIR__);$checks=[];
$read=/** Inline callback for this operation. */ fn($p)=>is_file($root.'/'.$p)?file_get_contents($root.'/'.$p):'';
$has=/** Inline callback for this operation. */ function($name,$path,$needle)use(&$checks,$read){$ok=str_contains($read($path),$needle);$checks[]=[$name,$ok,$path];};
$file=/** Inline callback for this operation. */ function($name,$path)use(&$checks,$root){$checks[]=[$name,is_file($root.'/'.$path),$path];};

$file('AW migration exists','database/migrations/2026_08_12_200000_harden_production_operations.php');
$has('deployment_runs schema','database/migrations/2026_08_12_200000_harden_production_operations.php',"Schema::create('deployment_runs'");
$has('incident_events schema','database/migrations/2026_08_12_200000_harden_production_operations.php',"Schema::create('incident_events'");
$has('MySQL incident update immutability trigger','database/migrations/2026_08_12_200000_harden_production_operations.php','incident_events_immutable_update');
$has('MySQL incident delete immutability trigger','database/migrations/2026_08_12_200000_harden_production_operations.php','incident_events_immutable_delete');
$file('DeploymentRun model','app/Models/DeploymentRun.php');
$file('IncidentEvent model','app/Models/IncidentEvent.php');
$file('Deployment service','app/Domain/Operations/Services/DeploymentService.php');
$file('Incident service','app/Domain/Operations/Services/IncidentManagementService.php');
$file('Production config audit service','app/Domain/Operations/Services/ProductionConfigurationAuditService.php');
$checks[]=['single merged VSN security config',substr_count($read('config/vsn.php'),"    'security' => [")===1,'config/vsn.php'];
$has('merged VSN security keeps SMS provider','config/vsn.php',"'sms_provider' => env('VSN_SMS_PROVIDER'");
$has('merged VSN security keeps CSP/upload limits','config/vsn.php',"'max_api_request_bytes' =>");
$has('worker heartbeat includes release','app/Jobs/QueueHeartbeatJob.php',"'release'=>(string)config('vsn.operations.release'");
$has('health checks release match','app/Domain/Operations/Services/OperationalHealthService.php','releaseMatches');
$has('health checks queue pressure','app/Domain/Operations/Services/OperationalHealthService.php','queue_pressure');
$has('launch gate config audit','app/Domain/Operations/Services/LaunchGateService.php','configurationAudit');
$has('launch gate active incident blocker','app/Domain/Operations/Services/LaunchGateService.php','activeIncidentCheck');
$has('ops API deployments','routes/api.php',"/admin/system/operations/deployments");
$has('ops API incidents','routes/api.php',"/admin/system/operations/incidents");
$has('ops API incident notes','routes/api.php',"incidents/{incident}/notes");
$has('ops command status','routes/console.php',"vsn:ops-status");
$has('ops command config audit','routes/console.php',"vsn:production-config-audit");
$has('deployment CLI begin','routes/console.php',"vsn:deploy-begin");
$has('deployment CLI complete','routes/console.php',"vsn:deploy-complete");
$has('incident CLI open','routes/console.php',"vsn:incident-open");
$has('incident CLI resolve','routes/console.php',"vsn:incident-resolve");
$file('production env template','.env.production.example');
$has('production demo disabled','.env.production.example','VSN_DEMO_SEED_ENABLED=false');
$has('production worker required','.env.production.example','VSN_HEALTH_REQUIRE_QUEUE_WORKER=true');
$has('production scheduler required','.env.production.example','VSN_HEALTH_REQUIRE_SCHEDULER=true');
$has('production queue pressure required','.env.production.example','VSN_HEALTH_REQUIRE_QUEUE_PRESSURE=true');
$has('sandbox payment disabled','.env.production.example','VSN_SANDBOX_PAYMENT_SIMULATOR_ENABLED=false');
$has('sandbox shipping disabled','.env.production.example','VSN_SANDBOX_SHIPPING_SIMULATOR_ENABLED=false');
$file('production preflight script','scripts/production-preflight.sh');
$file('release script','scripts/release-production.sh');
$file('rollback script','scripts/rollback-production.sh');
$has('release takes verified backup','scripts/release-production.sh','vsn:backup-create');
$has('release runs forward migration','scripts/release-production.sh','migrate --force');
$has('release atomic switch','scripts/release-production.sh','mv -Tf');
$has('release runs launch gate','scripts/release-production.sh','vsn:launch-gate');
$has('release automatic app rollback','scripts/release-production.sh','VSN_DEPLOY_AUTO_ROLLBACK');
$checks[]=['release never auto rolls database back',!str_contains($read('scripts/release-production.sh'),'migrate:rollback'),'scripts/release-production.sh'];
$checks[]=['rollback never auto rolls database back',!str_contains($read('scripts/rollback-production.sh'),'migrate:rollback'),'scripts/rollback-production.sh'];
$checks[]=['cron has no backend path',!str_contains($read('deploy/cron/vsn-scheduler'),'/backend'),'deploy/cron/vsn-scheduler'];
$has('cron merged root','deploy/cron/vsn-scheduler','/var/www/vsn/current');
$has('supervisor merged root','deploy/supervisor/vsn-worker.conf','/var/www/vsn/current');
$file('systemd worker','deploy/systemd/vsn-worker.service');
$file('systemd scheduler service','deploy/systemd/vsn-scheduler.service');
$file('systemd scheduler timer','deploy/systemd/vsn-scheduler.timer');
$file('AW runbook','docs/PRODUCTION-OPERATIONS.md');
$has('admin UI deployment evidence','resources/js/pages/Systems.jsx','systemOps.deployments');
$has('admin UI incident command','resources/js/pages/Systems.jsx','incidentAction');
$file('AW feature tests','tests/Feature/ProductionDeploymentOperationsTest.php');

$fail=array_values(array_filter($checks,/** Inline callback for this operation. */ fn($x)=>!$x[1]));
foreach($checks as [$name,$ok,$path]) printf("[%s] %s (%s)\n",$ok?'PASS':'FAIL',$name,$path);
printf("\nAW production operations audit: %d/%d PASS\n",count($checks)-count($fail),count($checks));
exit($fail?1:0);
